apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mirror
  namespace: mirror
spec:
  project: default
  source:
    repoURL: https://github.com/Sanlys/kubernetes.git
    targetRevision: main
    path: cluster/prod/apps/mirror
  destination:
    server: https://kubernetes.default.svc
    namespace: mirror
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
