apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: archmirror-pvc
  namespace: mirror
spec:
  storageClassName: rook-ceph-block-hdd
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 180Gi
