apiVersion: batch/v1
kind: CronJob
metadata:
  name: mirror-sync
  namespace: mirror
spec:
  schedule: "31 */6 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app: mirror
                  topologyKey: kubernetes.io/hostname
          volumes:
            - name: archmirror
              persistentVolumeClaim:
                claimName: archmirror-pvc
            - name: mirror-script
              configMap:
                name: mirror-script
                defaultMode: 0755
          containers:
            - name: mirror-sync
              image: alpine:3.23.3
              imagePullPolicy: IfNotPresent
              command: ["/bin/sh", "-c"]
              args:
                - |
                  set -e
                  apk add --no-cache bash rsync curl util-linux ca-certificates
                  echo "[mirror-sync] running mirror script"
                  /mirror.sh /mirrors/archlinux /archlinux.lck rsync://mirror.neuf.no/archlinux https://mirror.neuf.no/archlinux/lastupdate
              volumeMounts:
                - name: archmirror
                  mountPath: /mirrors/archlinux
                - name: mirror-script
                  mountPath: /mirror.sh
                  subPath: mirror.sh
              resources:
                requests:
                  cpu: 100m
                  memory: 5644Mi
                limits:
                  memory: 5644Mi