apiVersion: v1
kind: ServiceAccount
metadata:
  name: snapshotter
  namespace: snapshots
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snapshotter
rules:
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources:
      - volumesnapshots
      - volumesnapshotcontents
    verbs:
      - create
      - get
      - list
      - watch
      - delete
  - apiGroups: [""]
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list
