apiVersion: batch/v1
kind: CronJob
metadata:
  name: snapshot
  namespace: snapshots
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: snapshotter
          containers:
            - name: snapshot
              image: bitnami/kubectl
              command: ["/bin/sh", "-c"]
              args:
                - |
                  TS=$(date +%Y%m%d-%H%M%S)
                  PVC_LIST="mirror/archmirror-pvc monitoring/prometheus-monitoring-kube-prometheus-prometheus-db-prometheus-monitoring-kube-prometheus-prometheus-0 monitoring/storage-loki-0 syncthing/syncthing-config syncthing/syncthing-pvc vaultwarden/vaultwarden-pvc"
                  for ITEM in $PVC_LIST; do
                    NS="${ITEM%%/*}"
                    PVC="${ITEM##*/}"
                    SNAP="${PVC}-${TS}"
                    echo "Creating snapshot $SNAP in $NS for PVC $PVC"
                    cat <<EOF | kubectl apply -f -
                  apiVersion: snapshot.storage.k8s.io/v1
                  kind: VolumeSnapshot
                  metadata:
                    name: ${SNAP}
                    namespace: ${NS}
                    labels:
                      pvc: ${PVC}
                  spec:
                    volumeSnapshotClassName: csi-rbdplugin-snapclass
                    source:
                      persistentVolumeClaimName: ${PVC}
                  EOF
                  done
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 200m
                  memory: 256Mi
          restartPolicy: OnFailure
