apiVersion: ENC[AES256_GCM,data:w8Y=,iv:GKUou82h+lv2Evqpn4xWnYojSTe1aoGmwTEJoH+lN5k=,tag:oEz8xzt5nM5Zw4FLTjAoOg==,type:str]
kind: ENC[AES256_GCM,data:KRTB4M4F,iv:8960XrfC/MIDlCA5z3mM4jVxPFhWKGNR3TfDP50s8Iw=,tag:DQp6x0H2n72PZ6LQNJI7cw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:I8goZBoZEvUm3nQ0jKk=,iv:yjStIGZex+cfPs4iUfsqgA4fNS1uWBMqIBHV5neYsC8=,tag:w1yz688GQDBQJdQepdXaxA==,type:str]
    namespace: ENC[AES256_GCM,data:Yb33zO7TLzDkGFi5,iv:T9shYv9ZzhijyqPUzTZFSVzGPbjY9vFVF31TSmIUwN8=,tag:/1AAvVMqezr37s9APS6nyg==,type:str]
type: ENC[AES256_GCM,data:XsZ49Cjq,iv:bT8/C76AdNCkel6L6rnSjoobIh2Tl24+D+PdV9uiUsk=,tag:IvnsRBPSyrNjRe/c3zgv4g==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:9eZKuvoY0XhaT66ClBgCEKu0Fn0Cpq3YcNzniSOOszZLnmloOY2tag==,iv:hDE/n3Y9FUQluDD65f4BDn7TfcWp6NrRtUFATBDooaw=,tag:apyNhyLMZUDAc7wLHafM/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE9hRWxSdyA1dkgv
            V3p6Y2lYSndiWTFVMzJqK3NhK2ZyZjB2SEEvMkFvdEZiV3RXaEhnClU2OW96c0NN
            Zjcwa0NyR2FGZFdRdXZVenAzcmFwUGNKOVg3ZzJ1TlhGZDgKLS0tIHVLSERnWG5N
            dlo4L2VJaFFLMGZWMHdkakRxZmZ6N3lweGk4TjRkTTk0ekEKG/IPPNgzzJo2h0+L
            SlP3qBVGSBbfF4HB3uV47ceSdVZPLXFmkw1BkchYiYkwpM22BlxtxEI2ah7u7yI2
            jWa33w==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvT+ITNOzjlDdcTk9kdYLrGYd0EJw6kMr6Ynw9165wR sander@nixos-laptop
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHZpQ3Y3dyBmRFh0
            R1cwWnB2VFhyTjN6MktSYkllMnNaY1dmRWt5OTR2Z3dBSFBnYm1vClRobHd6cUtn
            YTRjMTRpbVpSeHZnNW5PTFF1UEF3eWUyUDZYcGoxandSS0EKLS0tIE5yVCtkNDlK
            VHdUVVJibjRuLzdwR3NVbmVRZ0F3Rkt3aEhLWXQ2cjlNQXcK+H/iu40uVDqHq96f
            asiPUbMbGHaHX8FrylN5yhpHqN51xmSK2/bJzTg/5KUT9tadUMg9iPYJ8nH5hgB9
            A4+zBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGhMesnzIJ89Ic38a3cOFUtiqE/No4FRFkhX+IqIIO3S sander@nixos
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IElVbEhTQSBxR0lB
            QnBZZThTaFd0MkVtVVNGN0tocUM0UDRYakZFcnhKSCtVYXhydFFjCkI2UHZEOThV
            Ym9naHM3UytOd2NPTGNqcUxkSWZ2SFdocXdMeExHd1dVNUUKLS0tIGhxbFMyK0Ri
            Mld2b2c3S29OeVRQdXlWRldjQzdITXRSdnh4cjNQbC91N00KwFxCg1r2WbIsm128
            0HuIpKKgbfQVv9M86CMTj+Nzlz39Ce4x026s+ctOWW7BdyklM0oCGz/J6LBrqeQl
            JTygJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFHe3wCRa3OBsJZJsnXgDDbWaIB18hq0RKUzU1eGqoco slysa@asus-proart
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFBtM1RTUSAyaFVX
            ZzdTb1NJMmVvTDFRMHBTWGkwcUYxbXJmUi9ZTk5YZFR0cXhpWVIwClJvdUJua3BJ
            ZThPOFB6ZnBUS2JDQmZPM0J3ckhKazVZcjZuTUlZTHVRN1kKLS0tIEdJMFlrb3J0
            YlI1SWxZcEt3M1AxbnNUYjJIR2NnTU0wLy9mUTBocVYxUHcKxuoL3qOWrmjOyda0
            c2R6hXXUSP1mzSsRxWir64FXHBe/S74zM/Cr0+XM8LpnS36iHfzuoOPfI3cUumNb
            CT3XSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB3+7P7YnvA6ghkemNkLLwoFZL/oTBLUOIz8K5SyQwS6 slysa@desktop
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoU21NelAvMVA5elVBL2Jp
            U2xXREFNNlMrSkNKUWQrL2tieVNKVnFkRlFNClFjUDUxMm51T2hZbmoxYkVEL08r
            MGNoSDQyZ0d4MmZkaE5XUFMvZEJyV0EKLS0tIG9oYW9kazZxblU5R1h0K29tYlph
            NTFlQWh3VTc2alVDaXB1djhkeXdSZzQKi94V6p1wznPjGT+GCgK9oJZwJg/S4xif
            cLQsgUR8i84PKG+DCeBZQIDbRnMd6DTYJy4x8dT7fZexq10DuJpKFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age185wsded9nj5vsw58saezfj8wekkftmpsrhv9cd05ep3k5vap8ckqc9epjn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG1XOCttdyBlV0dB
            SDBKZkI4ZTAvS1Foc2xyU0ZNdCtFS0JMVEtmdk5aRUd5VUpUVGxnCkphVk9vdXFo
            MzlEc0taYnRtTjJsWnRnMTc3VmlMMm5OZk1VZVlxWEVYdVEKLS0tIGpxcktDUGpN
            NHBueWUvRzg1TXZycEZHeVUvZTRORldYRFBuSGdZZUgrSTAKPsM+5DGuh0ki2+5V
            C/MMHcPnUEta4yN+u8ssjE5GMJR6pve8I0dqzFBEeYb+A1APY5Zmo542iE1e+/8E
            32F5Sg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL031Q1Dd6yu310sGwE4++BdJIad4gApbWlsPpMI8Mcx sander@linux
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDEyU043QSB5WGpv
            VVNDMFN3Zm9QNFNzcmMwWHdqVk9ud3BZSi82TjlBU01INm1EWTNJCmRaTFZnTVFa
            MDIrZkZWem02eGFwVGtINWgweEloaFdoUlpsNXJUMXEwRlUKLS0tIEhsM1B5SDBk
            dDFqdmVPQzM4MklTM1hNaXFkamx4UXY5NkgwU01qRWRPWkUK+Bjm4gmBNqFBbjeU
            3HqM/BkVoI6p71hZIxtkgSFLKdWYekeq+uOpHa70Zq3fbCWLzHr2L423NYUnNTE8
            zlxsTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPXFrU1bBLmiCk6/kDtrY8hBwZH1G3aLo8w/5psKz6rz sanlys@nixos
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdqWWNkdyBzM3JR
            N25FL3NOdGEwRVVpMG5PT0xSTTJadnVsOGRFTW9PcWZ5T0JWU21VClhnMWtaZmhI
            akdyM0dWbzBjaUttSmxtcmgyZUcwMk5KbWJVWUM3cm13NlEKLS0tIFpkbXR4T1J1
            ejRodEhiYXhoaTdSM1FMaHhSbXFlYU05SkUreWVvTjRQK0kKkwb9NT0VikygTDqL
            W+F1umzmN4Rg7GBmfFp9y/80ZboMNIh0AAjH04QXRwtjjW4eADbcO1gIgGnDxU9d
            DPLIaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJxVXIN2uJgZC7mU0yZXHkEwp9VPTnlO4pEHVWs/7KXa sanderlysakermoen@Sanders-MacBook-Pro.local
    lastmodified: "2025-09-21T20:44:28Z"
    mac: ENC[AES256_GCM,data:5ixVAaGd2D2u8Ws1ZUCM3GLJ3Tci/ias1gaK+T8lONXb9R8DobqcIPkKZ+G9Ra9zILDJIEg4ArLJDSp+p0X2lsA25o09bY+Y8jaABDSdMJRn+QMb9DWZU3fe9gE5OEE+nMWapNgfK/xq+avca2sENXKfGyupZO3MbaPY97ghhLg=,iv:VV1O7B+ileBA0hRr0vBgjOIq8nrm7Txa3pBkjHLU3gY=,tag:TsWyOTncvkhxsBtV4qxDQg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
