apiVersion: ENC[AES256_GCM,data:w8Y=,iv:GKUou82h+lv2Evqpn4xWnYojSTe1aoGmwTEJoH+lN5k=,tag:oEz8xzt5nM5Zw4FLTjAoOg==,type:str]
kind: ENC[AES256_GCM,data:KRTB4M4F,iv:8960XrfC/MIDlCA5z3mM4jVxPFhWKGNR3TfDP50s8Iw=,tag:DQp6x0H2n72PZ6LQNJI7cw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:I8goZBoZEvUm3nQ0jKk=,iv:yjStIGZex+cfPs4iUfsqgA4fNS1uWBMqIBHV5neYsC8=,tag:w1yz688GQDBQJdQepdXaxA==,type:str]
    namespace: ENC[AES256_GCM,data:Yb33zO7TLzDkGFi5,iv:T9shYv9ZzhijyqPUzTZFSVzGPbjY9vFVF31TSmIUwN8=,tag:/1AAvVMqezr37s9APS6nyg==,type:str]
type: ENC[AES256_GCM,data:XsZ49Cjq,iv:bT8/C76AdNCkel6L6rnSjoobIh2Tl24+D+PdV9uiUsk=,tag:IvnsRBPSyrNjRe/c3zgv4g==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:9eZKuvoY0XhaT66ClBgCEKu0Fn0Cpq3YcNzniSOOszZLnmloOY2tag==,iv:hDE/n3Y9FUQluDD65f4BDn7TfcWp6NrRtUFATBDooaw=,tag:apyNhyLMZUDAc7wLHafM/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE9hRWxSdyBNWENp
            dVJ5RllDbEZSR0YxL2ovekFpcG11RmFjR0FRZkM0U05Hc1pHaEM4Cjl2UUMwejF4
            OS9aUm9DMUtkdXBiNWs1eVlJSExwMDI3L1VyMXBEV245OVUKLS0tIDlyMnZzZ2Ew
            WnVFd2pFMlNKYW51U2RMbHpIelRNMTFJSUpaQUhnODMxQTQKbLQMbjLNmSc85uLX
            yBPPUkAcXXIAS8GKy1Meb77pmryVBEwRyszmdgfPKSU2mfCbEIcO8HsngCBustRs
            1RvGbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvT+ITNOzjlDdcTk9kdYLrGYd0EJw6kMr6Ynw9165wR sander@nixos-laptop
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHZpQ3Y3dyB4MnZQ
            eUp4cTF6UlFMQWozRjZ2OXJ1L2tIRzVuSVo1S2RYQXI4ZFozTVM4CjI3c1c2NmI4
            NVBST1R6WDU0eTNTZ2lPYmsxdGpYT3JLMHZqZFdueklqY1EKLS0tIG9oNEJlakxs
            RFJHWUpuNzdlQzJ2UEdaL0s2V2M5OStMU2JpNVBrZWVTLzAKNa9jOwqpwIxWA1Pe
            MBaVyjesq1/gUG3L1GxvppQUn+GulMtuBn0UnITF8jKWYU0YN3OaJf4AP0mMAvo6
            rQuTzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGhMesnzIJ89Ic38a3cOFUtiqE/No4FRFkhX+IqIIO3S sander@nixos
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IElVbEhTQSBBc3k0
            b0ZLOGw1Nkdyd1p0WHRCQjlDS0xURnF3R093MDB6dmpqdHB2R1Y4CmpsOVRhQWl1
            VmZjRmR4U1VCc256QjYwNnh2RGtFbVVzR3ZpMVNodnFialEKLS0tIEM3cVcxZ0tM
            Q3RSeTZuZUJFL3A5SmFaSmhLNWZ4djhXNE5sWHdmM01HWUEKW/tVHq+e4KBtu186
            V+OpOZxgWJth7oRCFtQNqb/TtYUd1jmwv9lhn5xqtM4f4MF16TCJmVH9c1qF/Srh
            xvjI+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFHe3wCRa3OBsJZJsnXgDDbWaIB18hq0RKUzU1eGqoco slysa@asus-proart
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFBtM1RTUSBTOUc4
            R2pXcnFLZGtkZUJsRlcyRVpEa2JkZ1JDNTAyNE9Fam5DNjFkNndrCkVoUmxrR3hX
            d2oyMm5LcUlFUXFpd2xad2tiNFo0OWlha3A2UGdTQUo4ZjAKLS0tIFN5azVKeWo4
            ZmdJdTFXL3lKa2Uvb01pWXpOMlNUd0VDQ0o1UWlLWEJuZ0kKvmRkmiXr538tK2NA
            5V5aQ5OsOK70W8v3a8g21JP4TFS+NlVZ/7tIBKN/GDV2kAJDWPQO0yulU0+IIZE1
            PM0q3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB3+7P7YnvA6ghkemNkLLwoFZL/oTBLUOIz8K5SyQwS6 slysa@desktop
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UjBJaUpLRHA1dEhHenJk
            WTY2SlFUY1pVa01mL1RjMmdwYWZ2TE5IVDEwClRzNmlKWlNZOUhhNVczWi9HMkFW
            ZkljbUVOZ3k3UHN0UWdLTlVZby95cUUKLS0tIFdMTElBSWpGdUdQelNNRjZJSlhM
            cW1CTEU4SWdIV2kvOTdtb0RraXZuekUK5yhXXN7ba7FiNzLEOtLMqYS/OEvMchm7
            GdzPEgNSqWbJTKLA4ZRR11qhD9j5R53K6l/yvpBiuC29IpzyS8/QjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age185wsded9nj5vsw58saezfj8wekkftmpsrhv9cd05ep3k5vap8ckqc9epjn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG1XOCttdyBsWEF3
            WDQxL1puK0pneS9ienNLVmg4eFpYTjRTSm5aQWNwekVZTVdLc3gwCmJhdXpjOUty
            L0hKT21hRXp6dTJ3WUc5QjZhQWRHVzA3ci9IUHdxWkpwWjAKLS0tIEhwWGVUejlI
            am1FTHdKMW5lSUdiOW5YZkRMVUpSSHZBajBlZVQ0cTFXTU0KDUMjjSWfAXvxT8/V
            RQge2XMioLSZgvdiaWPWpnymPwhL1qS584M04lXon2ZjEuUnEtJKzySE5WzWlaK0
            s/gdGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL031Q1Dd6yu310sGwE4++BdJIad4gApbWlsPpMI8Mcx sander@linux
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDEyU043QSBqSEtV
            TUVLV3cxTVB6L3ZFOHp6TUFKcHUrbmJuc3hVVFJxOWVjUWp5cm13CkRHbUFyWGht
            OWp3Rm5mUk1WV1l0M1NZN016NXZ1ZmtYMGpnNXpXMEtzazgKLS0tIHpPK2t0bVZi
            eGxpNmw0djFxblN1MC82ZXhZMEVjNktLdGpMQ3hIb0J1U1EKrFqGcga9BwH/ZFS8
            2Zlt1ZebJZtGzW0B/gHKyv5LBxXq3SwvtOxg5WFDOUIthKugfm6Fa8Qn12tcSD/K
            UDCA4A==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPXFrU1bBLmiCk6/kDtrY8hBwZH1G3aLo8w/5psKz6rz sanlys@nixos
    lastmodified: "2025-09-21T20:44:28Z"
    mac: ENC[AES256_GCM,data:5ixVAaGd2D2u8Ws1ZUCM3GLJ3Tci/ias1gaK+T8lONXb9R8DobqcIPkKZ+G9Ra9zILDJIEg4ArLJDSp+p0X2lsA25o09bY+Y8jaABDSdMJRn+QMb9DWZU3fe9gE5OEE+nMWapNgfK/xq+avca2sENXKfGyupZO3MbaPY97ghhLg=,iv:VV1O7B+ileBA0hRr0vBgjOIq8nrm7Txa3pBkjHLU3gY=,tag:TsWyOTncvkhxsBtV4qxDQg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
