keys: &my_age_keys >
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvT+ITNOzjlDdcTk9kdYLrGYd0EJw6kMr6Ynw9165wR sander@nixos-laptop,
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGhMesnzIJ89Ic38a3cOFUtiqE/No4FRFkhX+IqIIO3S sander@nixos

creation_rules:
  - path_regex: ^talos_enc/.*$
    age: *my_age_keys

  - path_regex: secret\.yaml$
    age: *my_age_keys

