apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-central
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: database
    server: https://kubernetes.default.svc
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cluster
    targetRevision: 0.5.0
    helm:
      values: |
        cluster:
          instances: 3

          nodeSelector:
            cnpg-storage: "true"

          storage:
            size: 20Gi
            storageClass: cnpg-local
          walStorage:
            size: 1Gi
            storageClass: cnpg-local
          resources:
            limits:
              memory: 8Gi
            requests:
              memory: 8Gi
              cpu: 2000m

          initdb:
            database: postgres
            owner: postgres

        monitoring:
          podMonitor:
            enabled: true
          prometheusRule:
            enabled: true

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

