apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volumesnapshot-controller
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/kubernetes-csi/external-snapshotter.git
    targetRevision: v8.5.0
    path: deploy/kubernetes/snapshot-controller

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
