apiVersion: ENC[AES256_GCM,data:PJ4=,iv:CzUNbcuZkMUkKZJWiOlur+RcIcUvIADD8v0WXoGGRPY=,tag:CNU9BmSTUyX02HPT7ccgzA==,type:str]
kind: ENC[AES256_GCM,data:QboJmFsv,iv:l6k55G+nQqoPP/6nnHSsSQsv00dx8GNlVCcLlG8KKFU=,tag:6DbNQr/WAr3NkHdCc2NEDA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:sAYNUphlb8FWYz0=,iv:xotPrMZc9fvy1QWIcoMMbpdaudD6MgVeGMGE3QKZWro=,tag:ZwcCXwd/Gua947D4LdqU+Q==,type:str]
    namespace: ENC[AES256_GCM,data:CXfTVzn52ZXtKuDX6wLSg7yL,iv:gUl2ls/DxRy1ymbu3ocFs8rzpfWdAIyq6xkSwh5mAsI=,tag:ZjUj3lGKrw914ll4/r0l7A==,type:str]
type: ENC[AES256_GCM,data:c7sJV5L5a2qzcLH/4i+cRriOpttYAkNZTAoApwt/,iv:FKBjI6w4wqCiOFaU+oB86HzUPhbiy9dblNRdtPnDsAs=,tag:AwsnuX3RqcgIN5GcYGi4Nw==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:h27L/8ltZk7fs5mfRmYvzA9Tr2CwG4b5CrGSoWaZoOxkXsWpWL39gUBuwCVyZm1MClRHRWlLEPX/SA2sBxJNP0VoAD73nnSMJG6t4UwAOn7vMVTCjerqn3f8qqzSZPBplEsO9IuiVjHwpChsZ9Ur8XTyr6dJRu1D6cS28O4auIedjNYylPLC0WUNDmo30RWvdmLNkdPRLE+kyejUEkhDQbjauHaqd4VE53+I+A==,iv:lQatK51n1/m5gIIBs1N0ZN4/lXsxWLXYXb1N/sOD3TU=,tag:Mq89hfvD74qFz4EruYV0XA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE9hRWxSdyA4YSt5
            L2JRRjBNT01Wbk83NXJ2TmwwVExBTjFEZ1EwSnBMS04ybjE3b2g0Cm8wdmk5OEVK
            Z1ErUUpsbHM3VVU5WTNpVXliREsyczM1ZkJBb1NFaUdEaWMKLS0tIG5mTy8ySnVw
            UEloeGJLRFV5WkJrVjd6T01TOFJ3d3pRWmJhNkkvTWNzYzgKkTNaTYDNygFOqx6I
            B/ODyL2UpxywgWOJkFgTEbUdMgHwcJ3LDwABOpFn8advB40BTZ2KU3jtX5itl4XF
            kvGG+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvT+ITNOzjlDdcTk9kdYLrGYd0EJw6kMr6Ynw9165wR sander@nixos-laptop
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHZpQ3Y3dyBJVkdq
            OW8xS3ppK2tJYTlIYk1JMGdRaDdrVFpSNGFBamhzTDB2NGJUdUE0CktScnRuVjN6
            WmNYR2I5aXpTSEVwTW1xcDhnQzRPdlBPNk43a2U3dSswNU0KLS0tICtXYlpOWnZJ
            NXdaTEdlWEp2QjcyckE1U3hDUk8wbm5rWjdJTjZoSHJQRHcKfYG3pLqRUFtyBwpq
            k3DgaDcUAueT51+/E69OGwrOPcLP4Vt8vj31Rs/Y6Q3odIDPLbMX+EpyvFSGvsp1
            +5I99g==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGhMesnzIJ89Ic38a3cOFUtiqE/No4FRFkhX+IqIIO3S sander@nixos
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IElVbEhTQSBEaGVs
            QVk5a3FIWHJSZ3ludU5XcDlzZlltNHhTUE90RWd3U2ZEeUxVZm5RCjYxNnAxZXdY
            OFowNWc4c3NzRklpTWczYXFERUt2MGUxeTRXRkJyYWkxRTgKLS0tIFMxYVpQdGNy
            blpodXlMSVZYZU11WjhtR0RLKzR3bFVoMVhVQ1hpUnZGaFUKCj6FpZukjuSYKmiV
            ZHpy+dCfJzuLc5bIhwlDGcYn3xGxYXcQbEOq3ZAEMNqOdl8EEjGpqu8P0jcWx25z
            lfmCzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFHe3wCRa3OBsJZJsnXgDDbWaIB18hq0RKUzU1eGqoco slysa@asus-proart
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFBtM1RTUSBWL3RT
            UEhJa2FJOVhXTHdhanppWGZVbDVwdWdDVmlBeFV2NDdTOC9HdWtRClM5RmpsZlQ3
            NUdPN1RLMHM2VVNqM21VMmtUZHR5WnRNZm1MSmVzMUdZWWsKLS0tIHg2dmpiY0xw
            VWo5bFFzTUtveGRMTFZqNkkvS1hIZHFzL3YvWU1SL1ZnRjAKtaQzygaIDhFuWp4o
            JXBYdoh/MPwuW6uSOiFGImjyVZQpN27Bh2OuXdoFn5BqQNjZVdo8dCz4bZY6kM/k
            ZxKNyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB3+7P7YnvA6ghkemNkLLwoFZL/oTBLUOIz8K5SyQwS6 slysa@desktop
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRjNWOEczMkZWcU1STFYy
            YWZtZFppQUNtUTRVZ0JMOERNUUR6c09tQldRCm5nTGs5c0pBc0RvWktINUFCWGpj
            d01YTForWnVxSk0vQW84Wk9ocmI2L1EKLS0tIHBlZWhzcGEvR0tFbjdIMXoxc1pl
            aFY0ZGVOdnRJMEpERGIvU214ZG0xdDQKcUYCuWpdnDdIcJKGhZ4Ht9LOdoaM1HXu
            8qnXJlv3ihI4CANAR2UB7XfsanuA1iTkxahuICAxy+hWXNK0oE2qaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age185wsded9nj5vsw58saezfj8wekkftmpsrhv9cd05ep3k5vap8ckqc9epjn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG1XOCttdyB2Vkt3
            SFY3QXNXNVZOZ3pCUENoM0RGckpSZlQ1S1FPSitYSjQ1Z0YvYTJBCmhodC9aQ3BC
            dXp2QndWMXVsNVJvZ1dFUkFuWW41K1NINGlPVlg0dnZxSEEKLS0tIEJiWlUvQnpO
            ZnhiR2FoNVBzVS8wY1hxYUJLMUhLNEM3cVdYWm5wTnBoOFkKQnDB4GRX7CgaYr7G
            kJmVe3AX5vQe0GGK7QocvvvIk6Ta5bLxcRB1yrHhC1gejFqEb1Fk4igE9Q0eoH48
            MfiQDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL031Q1Dd6yu310sGwE4++BdJIad4gApbWlsPpMI8Mcx sander@linux
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDEyU043QSB1L1d3
            a3owQlk5dk9CeGdKUEI1SitEdWxUcG10SnhpZWxXeTgvU1FFaWpFCjhGV2tKOFg1
            aFhjb0lMbE1SZlpOQzNEU3BkUEFWYzJkYTduWDI2WUtaaG8KLS0tIEhZWS9iOHNy
            b0x2d3pkTEhGdTFuRW8wQXdraTd4WUNmNVNXWHNPQlJ6Y28Klovz9Gg4DKFcrMiO
            1/zw1TpbiUoWv1uL9F483QVtxL9IBGSnmageGgQ9iYMYLSf09Vmqx5PBey6dWoo1
            I68v8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPXFrU1bBLmiCk6/kDtrY8hBwZH1G3aLo8w/5psKz6rz sanlys@nixos
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdqWWNkdyA5bHUx
            bTdJMlhHTVFybDU5TldmN1pMMGdPZmpSdDRVZElEWFV6NFBFN0NvCmZSa0czWnp5
            TkllcTNYend6ejE5dGRDbURVWkE4L1oxbXBJNUUxSTBrR3MKLS0tIHhVaU4zMDB2
            TzV2U2VVSGw2U1N2STA0WW05M2k5S2dPRVZ0dEZJeEx2eVUK/LeHDwjyJ+Ja2roF
            NC49O+R6b+WjJwPXYId3x5fKIQZEKX18abbjBQ1vVIhoTtkGK25ygEaBoSmNvQ49
            QMVnKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJxVXIN2uJgZC7mU0yZXHkEwp9VPTnlO4pEHVWs/7KXa sanderlysakermoen@Sanders-MacBook-Pro.local
    lastmodified: "2025-12-18T10:46:16Z"
    mac: ENC[AES256_GCM,data:BIFSd8xqWIB8jhgX5tMpyU8QHF3fXIJu3dDPrmjtjRpDGgCpTIW1Kyq5vxTUwJ0/85awU401/P4VlebvsfuYMjotCjPs2usS3KsX0XlirBV+Vn89C3RlaieLxdS19nu+YLaodIyQa4wLUHyoDGWGxxvH+GtxldNOfuHlcSyHE/0=,iv:OvrfGIH7A8Tz4fYQeO/0j4Lvl0aVVHrB8P/qfgeKi10=,tag:ior4AdKoPyb4NRfs+oTHlQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
