apiVersion: ENC[AES256_GCM,data:PJ4=,iv:CzUNbcuZkMUkKZJWiOlur+RcIcUvIADD8v0WXoGGRPY=,tag:CNU9BmSTUyX02HPT7ccgzA==,type:str]
kind: ENC[AES256_GCM,data:QboJmFsv,iv:l6k55G+nQqoPP/6nnHSsSQsv00dx8GNlVCcLlG8KKFU=,tag:6DbNQr/WAr3NkHdCc2NEDA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:sAYNUphlb8FWYz0=,iv:xotPrMZc9fvy1QWIcoMMbpdaudD6MgVeGMGE3QKZWro=,tag:ZwcCXwd/Gua947D4LdqU+Q==,type:str]
    namespace: ENC[AES256_GCM,data:CXfTVzn52ZXtKuDX6wLSg7yL,iv:gUl2ls/DxRy1ymbu3ocFs8rzpfWdAIyq6xkSwh5mAsI=,tag:ZjUj3lGKrw914ll4/r0l7A==,type:str]
type: ENC[AES256_GCM,data:c7sJV5L5a2qzcLH/4i+cRriOpttYAkNZTAoApwt/,iv:FKBjI6w4wqCiOFaU+oB86HzUPhbiy9dblNRdtPnDsAs=,tag:AwsnuX3RqcgIN5GcYGi4Nw==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:h27L/8ltZk7fs5mfRmYvzA9Tr2CwG4b5CrGSoWaZoOxkXsWpWL39gUBuwCVyZm1MClRHRWlLEPX/SA2sBxJNP0VoAD73nnSMJG6t4UwAOn7vMVTCjerqn3f8qqzSZPBplEsO9IuiVjHwpChsZ9Ur8XTyr6dJRu1D6cS28O4auIedjNYylPLC0WUNDmo30RWvdmLNkdPRLE+kyejUEkhDQbjauHaqd4VE53+I+A==,iv:lQatK51n1/m5gIIBs1N0ZN4/lXsxWLXYXb1N/sOD3TU=,tag:Mq89hfvD74qFz4EruYV0XA==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvT+ITNOzjlDdcTk9kdYLrGYd0EJw6kMr6Ynw9165wR sander@nixos-laptop
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE9hRWxSdyBTVHBX
            VGhWcnBMNGtWUzJ3YklpTFk3aTBPaUdLcU55ZTBUVnkxTWxhcXlBClBYR3lsRU1t
            YXQ5bjdUZTdncDVSZGg3SlJCRzdnSjJUbzdadi8rdWE1cDgKLS0tIDd6em9LQW1t
            bWhlY3JaZ3JKV0tKWFJTVmdZbnJ6Nk53MFVqMGtseEdrVVUKGg0Ft4FNK69exU19
            1q/kkoBJiL0Y7MA3bGp18h29Sp6ta6GhC9uwT3AbLAimOgX8f+j/EefFitoIk1EX
            dDhTOw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGhMesnzIJ89Ic38a3cOFUtiqE/No4FRFkhX+IqIIO3S sander@nixos
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHZpQ3Y3dyBQbWti
            QlhjbEprbEE4eVFDUzlxTjN5dHpkSkJ5RHVTTjk3bXp0RTlPT3djCncwN2loRHFP
            eTZ5MDlyVFYzU2JhNGhJWUVIK3luYlpWS1hLczdsZlNHc2cKLS0tIHZMQ3JKOGJl
            UE02SUNFekczSDI2Mmt3WFJQT0dXS2ZIRk50cU5EYytGQ1UK/lWEQVo3ukhxZ9dd
            lCQRM3OGua1TfXbIGIm2yjWP9I+PA3wa88Euym1lYocClJwoQPBK1Y5Lqt/fATUE
            ArsGVQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFHe3wCRa3OBsJZJsnXgDDbWaIB18hq0RKUzU1eGqoco slysa@asus-proart
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IElVbEhTQSB3a2ZZ
            T1VXaFAyN3RwZGhjYzVFTEc5bE9IYng1cHdxVmVJTFUwNkpmUHdFCkc5Q0tSSnBo
            UGw5U3JySTFEZ25QRDk1Mkh6cUpmQlZ4NlVuRWpVYWx0dGMKLS0tIEVwT3ZyS0t5
            b2cxL2lNRTZJNldFcnNtaHMvekd1akwrVU1vMml5SHFYY00KcdBio/GqZEfutjRG
            kGGWC4WDZw9DIc/+jMOfZqJIRxVNiunw5cOKKWACTQyEWPqmiWTiJop+61btYbW3
            Ch8g4w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB3+7P7YnvA6ghkemNkLLwoFZL/oTBLUOIz8K5SyQwS6 slysa@desktop
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFBtM1RTUSBMNFhN
            TnM4U21Ec3BrdC9UdTRwd29vWGZHN0E2UnZrV29DUmJDVEgrWEV3CkVaRzdVN1Jh
            M3JhQ2xFTUhVWGIrN3dmRE9xL1VONnNKVFNPWTNZRWJvSVkKLS0tIEhINm1uSFpI
            M1I1bzhFQVZiQXNKbW50ZENGN0QzcDBXZWpVb2FuWHZJYXMKqT11J+j6pzV6cPdS
            GUGRTGGW481BxcPMe/eBVQCYJZZvF8QLzsKAq/aR9V8MDjvJZCmcfTVEw2gBjs1O
            05m6Gg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age185wsded9nj5vsw58saezfj8wekkftmpsrhv9cd05ep3k5vap8ckqc9epjn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3S09VN3JQcVVnZGc2VlY3
            QXBmcTZZYlJpbVR6djFUUzdGTnRZM0RWMUVBCjV0VlBpTTJNY203bGxVWW5wWTZM
            R2p5bDVsaGVzL2FlbXI5TzB0MlJOZjgKLS0tIGZhck13bXBpVW11aTVjMUhtSU5m
            dk9KSFYyUG9xVHUwREdaWmhvejhzcTgKPDa8nvXcM9q6eqBgAgbIHerCnR9znNL4
            zo+FMm9HTTOK30UdajxIqdGL+MwOyxlnBillU/6mZ4/vnmjteeLhHQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL031Q1Dd6yu310sGwE4++BdJIad4gApbWlsPpMI8Mcx sander@linux
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG1XOCttdyAvRTk4
            d1BId1dzN2RDL2FsSGhldkRJZVIySEorZHg4RnR5S2JMQ2I2M0NFCkFUZXFtRity
            WVZJYUhsTEYwNituSm9jSDNpSHlEeUZxUmI0TzNNcDlQdk0KLS0tIHhmUmI3VllW
            M1diRGlCVW53aVJQVkdMRkZoKzdhcE1TWUhhUEJkcW1MYTQKFbhpgtAa/fB931sO
            yyX5mCOuWc5NowmNnrIzaBDaXmMSgF+earY8T0yw5eTaMIKr1Rwv4tfdsqcIQYFL
            lYFfGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T10:46:16Z"
    mac: ENC[AES256_GCM,data:BIFSd8xqWIB8jhgX5tMpyU8QHF3fXIJu3dDPrmjtjRpDGgCpTIW1Kyq5vxTUwJ0/85awU401/P4VlebvsfuYMjotCjPs2usS3KsX0XlirBV+Vn89C3RlaieLxdS19nu+YLaodIyQa4wLUHyoDGWGxxvH+GtxldNOfuHlcSyHE/0=,iv:OvrfGIH7A8Tz4fYQeO/0j4Lvl0aVVHrB8P/qfgeKi10=,tag:ior4AdKoPyb4NRfs+oTHlQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
