apiVersion: ENC[AES256_GCM,data:PJ4=,iv:CzUNbcuZkMUkKZJWiOlur+RcIcUvIADD8v0WXoGGRPY=,tag:CNU9BmSTUyX02HPT7ccgzA==,type:str]
kind: ENC[AES256_GCM,data:QboJmFsv,iv:l6k55G+nQqoPP/6nnHSsSQsv00dx8GNlVCcLlG8KKFU=,tag:6DbNQr/WAr3NkHdCc2NEDA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:sAYNUphlb8FWYz0=,iv:xotPrMZc9fvy1QWIcoMMbpdaudD6MgVeGMGE3QKZWro=,tag:ZwcCXwd/Gua947D4LdqU+Q==,type:str]
    namespace: ENC[AES256_GCM,data:CXfTVzn52ZXtKuDX6wLSg7yL,iv:gUl2ls/DxRy1ymbu3ocFs8rzpfWdAIyq6xkSwh5mAsI=,tag:ZjUj3lGKrw914ll4/r0l7A==,type:str]
type: ENC[AES256_GCM,data:c7sJV5L5a2qzcLH/4i+cRriOpttYAkNZTAoApwt/,iv:FKBjI6w4wqCiOFaU+oB86HzUPhbiy9dblNRdtPnDsAs=,tag:AwsnuX3RqcgIN5GcYGi4Nw==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:h27L/8ltZk7fs5mfRmYvzA9Tr2CwG4b5CrGSoWaZoOxkXsWpWL39gUBuwCVyZm1MClRHRWlLEPX/SA2sBxJNP0VoAD73nnSMJG6t4UwAOn7vMVTCjerqn3f8qqzSZPBplEsO9IuiVjHwpChsZ9Ur8XTyr6dJRu1D6cS28O4auIedjNYylPLC0WUNDmo30RWvdmLNkdPRLE+kyejUEkhDQbjauHaqd4VE53+I+A==,iv:lQatK51n1/m5gIIBs1N0ZN4/lXsxWLXYXb1N/sOD3TU=,tag:Mq89hfvD74qFz4EruYV0XA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE9hRWxSdyBFZmx6
            V2doc29YdEtlamt0cytMMzMwYlJjWTJxK0lHNGUwRTNPS2ZiNEVJCk94RDAzK2VE
            bmRMM01mR0hJVVh6ZFZOZ2doekw3Sjd3N29QS0hxS29MWWsKLS0tIGNWQ3k5K1Vz
            dU5vUXdmdkRtVThHbTYraDY1elJlTGU5dWlicU5SeHFrOW8KAP9wRw8S5T0hCNye
            fwYy/ZBO6QdR0tfCu9FJkpWvIQTG6mry2Sv1pfr8zOYoIdUlqMr3eQD0aqtQlLYj
            kGwWFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvT+ITNOzjlDdcTk9kdYLrGYd0EJw6kMr6Ynw9165wR sander@nixos-laptop
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHZpQ3Y3dyBZN0Uy
            ZzdhUmRkVzFlRkV4ZnhrZjk1eXJ4SVlBS1dOeDRvbGpTYjFpbmlnCnZOdjlIenlY
            UGZBYTMzNWdJTnltcFZNZ3ZyR25vbnN6TzV2eWdJSm5Rek0KLS0tICs2V2ZWMEE4
            ek9PbjRjQlc4ejNrdVJ2bmxMdEFvNGc2cGhVbUFKREdVVXMKm4FZnaudsvFq1aAh
            PV9S/vXjAYLq7EyeFWKzcitkFYyqhcyeIgickpYBBrPyFMDi3pBDOy1kdITY6tuv
            AXJz7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGhMesnzIJ89Ic38a3cOFUtiqE/No4FRFkhX+IqIIO3S sander@nixos
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IElVbEhTQSA2QmEz
            SVJYRDBFbGc3VGI3QlZHa0x3QXdzcytxemswOE9ZWjRVQ0EzbDA0CjN2OFM3eVlo
            eXVMWCtDc1FkU1RzMTBwZDFMRm1SZmZrWEZQOXV1TWcxQ1UKLS0tIE1jOFgrR0lq
            eExDeEdSbjh6K2g3T3czMnQrQjhkeC9yYzJGVUlRWkdkQ0EKwtAHRsmN7eTIuVX1
            Kowj42TpknHmt7yU94uq1q+BN6Rn5xKTO7WNk/hul01MlXsWTzlzlh6V7dtYPEUj
            pvKpOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFHe3wCRa3OBsJZJsnXgDDbWaIB18hq0RKUzU1eGqoco slysa@asus-proart
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFBtM1RTUSBudUJj
            N2ZjVjBORUVFMGxwT3dKRUpSenpFRVN2RXhnU2pISFN5MytveEFRCjdERjlSZXNB
            ZElLaitYeEFQdi81ODltVDg5ME9jQ0dMdGNMbzNDWmxmV0EKLS0tIFFBd2RnY1RM
            bHhPbThLQXA0QmlSVE55WkFyZmdpSGtyb2ZZaGdQZE1HNFEKg2tA2FigBeiftdYl
            rcAqNufT+mByHLViXb3KdwXSaMn7RzY3EIb0J2YKHotqEd6C8s5108ZvkFfERZd2
            kOoQiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB3+7P7YnvA6ghkemNkLLwoFZL/oTBLUOIz8K5SyQwS6 slysa@desktop
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQ1I4UlBqU1ljZnRxRlB6
            bFNiYmxBYnppdWk3Qk1NVzJXejJWaGJSaHpvCkZETW9ibDFIYmg5Z2RjZUV4TnUy
            MkNsNk1GdWdZUTNrbjgxT21FNlRQc0EKLS0tIHhGSXlVVnRyeVFPSGpXWXZzT2dB
            UFdTbTVkdUlmL1Y5aDNQTXdKN2xVK1EKaOOnW6XYRC6svf6uwRamnaDVM5Sf3nLB
            TlXSxnlYluBaYJ/f/1tKW47V29GfvfVhL6+5XqtXh6I6i/wV9HNKvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age185wsded9nj5vsw58saezfj8wekkftmpsrhv9cd05ep3k5vap8ckqc9epjn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG1XOCttdyA3VS9K
            SjZMa0xKa0NFZGdic1JyMnlpaS9WSUxyVEkxcFIxOG5CMXBadEJnCkhZeTZML1J4
            OGNGaGF0aG9vbklXdzhKekNyT1djVDZncklIQVh6Y3lOQW8KLS0tIDdkd1pDcTNC
            VUxlTUdnWU9YM1RER3VZcVpodnBSMStYdWc2NDY2SWg4ZFkKfHf6NBO9aKFXMylX
            wz+/lipOkjK5C3S8OwJMBOo7V09UBR2UZzFadobECgGtuOGGqRopygM0hZmQEuH8
            V5nU6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL031Q1Dd6yu310sGwE4++BdJIad4gApbWlsPpMI8Mcx sander@linux
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDEyU043QSBwekx3
            UU5BRXdiM05XK0pOU1YvQ0dVMmVTdm1GclFUYWlHYkszamlXbjBrCmx6QTJnTXRG
            eU5HZGR3MkI5ZmdjVlZNS2I0RGUxT0hHZTZvMmppYzI1aGMKLS0tIHd4bzFPR0Rv
            a2JnVk0zRy92VjcwWVhXRGNheWpkTjhjUkV5eTdlVVRNNk0K7Tw+yDG6ao/e3gDR
            6j9g4kJsbYG0Ph7v4Apb7pBjJFC+sntFhBcD/bpEkRjIY1CaqsNGTmP1EuPYHdda
            wdARjw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPXFrU1bBLmiCk6/kDtrY8hBwZH1G3aLo8w/5psKz6rz sanlys@nixos
    lastmodified: "2025-12-18T10:46:16Z"
    mac: ENC[AES256_GCM,data:BIFSd8xqWIB8jhgX5tMpyU8QHF3fXIJu3dDPrmjtjRpDGgCpTIW1Kyq5vxTUwJ0/85awU401/P4VlebvsfuYMjotCjPs2usS3KsX0XlirBV+Vn89C3RlaieLxdS19nu+YLaodIyQa4wLUHyoDGWGxxvH+GtxldNOfuHlcSyHE/0=,iv:OvrfGIH7A8Tz4fYQeO/0j4Lvl0aVVHrB8P/qfgeKi10=,tag:ior4AdKoPyb4NRfs+oTHlQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
