apiVersion: ENC[AES256_GCM,data:4Js=,iv:m3BiSP0YILbAi+O/ahq7C27vIzioYACCfANZcq7vWhA=,tag:3YbjYK0fOj8L+2SDechnJA==,type:str]
kind: ENC[AES256_GCM,data:jrBoNmL8,iv:T2JpXfkbeqkBFGfvVqn9FerIuqXeOcWltwe0hUoVPNg=,tag:Cq+DHgUDWz3l0wfosZ7YEA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UPweYRW8z3EYWA9ETyY/nlBz7afFOUCCp6Ve,iv:0assTN/MEa1wx785aTvSBqO3cBKKYEm4ec+XdKKr4uc=,tag:3i0VTjHtf8Xq5K4Pl/WpKQ==,type:str]
    namespace: ENC[AES256_GCM,data:mmwky2ZxY9YXN/wt,iv:J6/UIFX4UnTD2npfjPckQvOoO6gQj+kTsrO16FPM3ZM=,tag:UOBm4Lnw3cObpcWoLzzo6A==,type:str]
stringData:
    UPSTREAM_ACCESS_KEY_ID: ENC[AES256_GCM,data:pekfwMXI3LffuOALHSllCSrQcz0=,iv:RBLzPDCUY82NHZjcFJAKQ48M6K07Zeq1rXbIyv5/OSI=,tag:69C0kDEDVSXnboyF/PcoVA==,type:str]
    UPSTREAM_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:hf08oLI7MgSERPQDddtominlv7LhB9453YIRJyImERNjyLv/oss8Kg==,iv:FY3XDaC2iS6H2FYNdzqcKc3zr68Jea/OCzaoE9XRLow=,tag:bIaz59NvwUyDnaVN2ZhRrw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE9hRWxSdyB1T1FC
            VU81dksxZ0trcWtSVzNzWnRkNm9RajFTSnRVMDRFYTl0eXFWUkM4Cks3SjZoZkdS
            OUVEUkorYWtvR1h5SlY4L25wUHFxSFNWanFnNG5WOUh1Q0EKLS0tIHg0UzRjbndh
            MVpRU0hnNTN5N0N5Zmh2NkZCeHJvNm9qODlxVHRVSGJpbDgKeiQWm2ZYp6LIhofr
            ox09zs8BsjQ+7LHiVNqJRInfWIudJpZhFMvS0coc8ZhJWlyXKTX5puDgVycxF9ou
            YtFrMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvT+ITNOzjlDdcTk9kdYLrGYd0EJw6kMr6Ynw9165wR sander@nixos-laptop
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHZpQ3Y3dyBLRlF0
            T0R6cHNxMGM4OHlWK0U2QkozUTA0RkRFZGlKbXVpMGJLRitNeHlFCnBZQ0FmdzNn
            NGZXTm5DZCtLb2pteVRqc3ZQamlMbGtucEJENkNsR1EvcncKLS0tIENpQnZZemNm
            ckxvTktpOWdZSzdyNWFwa0tYd2Vvb3hRRVdaRmZqdG0yUXcKddoqXXCbV9+hXu0o
            UQJEfc5+xSpaAbSqaQ0wg4z1POUZOUW01LmCSyiT+7FhdgCyQT7zeNwcp6Pxr2PU
            qvnrwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGhMesnzIJ89Ic38a3cOFUtiqE/No4FRFkhX+IqIIO3S sander@nixos
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IElVbEhTQSB2K3ls
            NGFlVEF1eG9SejlmVGNvL1dmUTdBOTJDNHV4MEZ3QUJ1a0VtSUNJCktzRmpLNzhh
            QlhhbHVIcTdWVjRqeExxTkcybkd3MVBnbnUwWDhVWkFEUTgKLS0tIE93OHRSaFZ4
            aXF2bThDa3cyVHVoVDQ3cktCcS8rMXo4TGl4STQ5T0hsaTQKU8W74EVlfSV1CE9u
            9VkDxZYUKx8CHVh+666luMaQP/PoQm4SRp2sy0/DUjkAYEjzMMXT/YK/PInIp2s0
            AHaqWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFHe3wCRa3OBsJZJsnXgDDbWaIB18hq0RKUzU1eGqoco slysa@asus-proart
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFBtM1RTUSA5NnVr
            Q1c4N2JkRUJRTDdoejJQSGcwY1lCTHN3eU1iU001bEtRUWdZS2dzCjV1OFVreUVS
            VlpkeFZ4QjRxOWVwS2hBR2phVVJtUmNZcklTdURBcDg1OEUKLS0tIHgrM2poKzgx
            Yk9sdWQ3ZVhtcGFzbWxOREk0M1Z1V3ozWlpQdzJkL2FWRDAKtdXME6KcuPgE76Yx
            uk1tcxWwUAWSuhHthyF5EPybBkUNIFgzqIG6DmwMJx/tMy17Hg++EZGE4rgEYBGI
            pVNWaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB3+7P7YnvA6ghkemNkLLwoFZL/oTBLUOIz8K5SyQwS6 slysa@desktop
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdHpvUDEzV1ZnQzJIRndU
            ZlAwM3hrZ1hCRUMrZGN5MGpBL0xWcThuNFVZCmRjT1M3VlZmdkptRXN3Z1hmZlVl
            dGQvUjlnZFVnSWFKeDVUOVZ5dHVsQVkKLS0tIENMY0RQWktHbGNxaThWVzBja3Nr
            a0xFa096VlFpQTVVUWt2K0JDaXZCS3MKYIsWHn7kR0WefTuYXWUgVD5WbU0aV2IC
            j2Ze11DKj0HhL2rAcbUQDPZmwIjrelJKUML+B9nzRFRj/FNZgT+gGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age185wsded9nj5vsw58saezfj8wekkftmpsrhv9cd05ep3k5vap8ckqc9epjn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG1XOCttdyAwMVk0
            cFNuV2daRDh0RWpSVlFaMFNpSkFUME1GWkRPa3V3SnVxckhDWFZBClQ3aHB1Z05Z
            Sm5yMGd3NDVlWGVtTW9FWlpRcTRTYVg3ZFUvZklrR1lOZ28KLS0tIElqTmdNNmpZ
            L0N3VEZacDdrVHFrSU5FQWxuZXU4L0lKT1h5bk1WWktFOE0KWLqevmcZbV/ZRfEc
            cIBjGhR/FBN6N6epS/MSlp985EMdruDA05lKpFQ3se11bWFUynqE6mdv+PzNi92w
            O2AWkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL031Q1Dd6yu310sGwE4++BdJIad4gApbWlsPpMI8Mcx sander@linux
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDEyU043QSBqSzlt
            M0JaK1ErRUViVitRaWxYdDBLUHVZeVpxNTdML0RZOHRwNmM5am5rCnBhajI4S2NS
            V1dCeTRrc2oyMy9zdU5oanR6eDVlUVVRdGtMeTZ2VVluNncKLS0tIFpSZnJUdWkw
            bWF2K2J3ejNUTldmSlZReXJaSFN0aEtlTHpYZ1loaStXcWMK/aRjZfBq6mn56xg0
            VlVixV/7NA1nV2NhhxujvQgqMCKxPgSQ6F5PJo6ifwbPwgz2rawUt43tH486rVzR
            rmlLog==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPXFrU1bBLmiCk6/kDtrY8hBwZH1G3aLo8w/5psKz6rz sanlys@nixos
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdqWWNkdyBwcVZP
            OU5zSlJoZzlORml1ZnpYZkxMTDBNSWY2STVySjloUUxiK0pJYkNNCi95NmEzODdO
            US9ZcWRtbDJRanFuZ3lhYjZJZFNia0VNQnhaL2I1YWFEeDQKLS0tIExYbWdvSWNE
            SHZ3U2pDbjJpQ1BDa2syTXV3Yi9seWtNSy9vTVp6ZXBoVGsKC7dSUKsuT4KTCeoR
            mr7TTiARlAkJxOD5Bn58IV/w389clWSkBQmw0djO0kSHeUPWZnQWZXNtBJHumstI
            xNLHaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJxVXIN2uJgZC7mU0yZXHkEwp9VPTnlO4pEHVWs/7KXa sanderlysakermoen@Sanders-MacBook-Pro.local
    lastmodified: "2026-09-20T17:21:21Z"
    mac: ENC[AES256_GCM,data:9oiNiqlIGVwApg7hXkgCMC9nNhcyURKXJKl78lRhepyr7bYdDwwnYOdR0CqgBRW0diThl1YLocUiZp8+hFvAToW6HtgKVXy4IzoglhnapEw8KzsuzYaKAdFU2P5ey2BSxbqIseGaPl3zx9pVy5moPHysRK+7fJ00EOIV41XxtkU=,iv:Kwekmzaha7RezM3yQEJJsXe3DDZF5Ea1cm9m9N54qm0=,tag:PZP/N+KBQ7I5b7GPuk/6yg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
