apiVersion: ENC[AES256_GCM,data:xZg=,iv:WEAGmZZwyzHrJnz36AWAlz+1RBEcKdRs/maBram4oac=,tag:dFWCfL2ZdIW+VEMMaILZfw==,type:str]
kind: ENC[AES256_GCM,data:RHRifWMq,iv:MVKO7L/vVh6fHWfK/aOQEQdz/q3SlIdkuedfvtXHeT4=,tag:o7uZdsdb3elqI2qmg5vs8Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Vx1r3aHe0CrNlu0yoewRmwhmMBA=,iv:5qubhhSmo628i8FLwgpiqEsQ2s85tyCc1bFWp1NRoh4=,tag:SrsjnkRKzEyAgQ5stpCrQg==,type:str]
    namespace: ENC[AES256_GCM,data:W57hrWQ=,iv:ulGics39ilctuetJfZJ5Gos2eOXDn3aGyYIWim9GKic=,tag:/ogncJZ88PHp6Nhws2Lxcw==,type:str]
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:5aIH0qdqZcjoQu4G3tlRQ4p9wTtNJut1dfLT8hygpClqFSeRRbLZ70HdgSI=,iv:hE+JtRJI0ZJO+JQwWoGnZFe5wprR0op5d2saPS1TPVU=,tag:BLL3oKaXGyAe9Uh9MBUaYg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:Q7Ok07BO71rrhdq081nbikip523ruy9gS1oVgMuaLmfpyqbVOHbix/ifI4fNJEeR,iv:Kyz5GReRnItNZwuuuPu+OqPCxZerB873xtVgPZdx1/c=,tag:GXhg0/HMUpyuSNPptDsaXQ==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:HW/X/LB/wVEC85j/w78bZDYG6AojcoQHWI3qVbb7PPdbIoTnB5wE4bd6nhA=,iv:W/u90Cy/JFouML5ycxYaSnJdn2lYiOQ31u930Nx0QKA=,tag:LwrQPLb77pbnNW8PcAxv5Q==,type:str]
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:rqnQzkOrLbNNQsNvQw==,iv:Jm05njI4micLq20eSgCobj220bHgNVKlWB6SLEJTen4=,tag:6EpVrnhVTL27r0TSDtNztg==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:fw/+71A=,iv:d6Sca6WilPMKT9y/yZWkcJvoxi2lJSkaNgiy1hAl8nI=,tag:A9RcBcmHl9RHvho0fePk8w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE9hRWxSdyBNZ0Np
            SnF0RDN6NkRwNDhPTFRJSUU3UDRxanBtNmFka1JScnNMQkhoL0hZCjU4MjAwVWpv
            RlRVbEp3RnNiWWw0bEszUS95T3dXUTR1Zi85NWN0UFZzTzgKLS0tIC8vVEtGNVc3
            WHNVd0ZVUThxSUxleFhDUjVCdnNoK2FqVXdvTEhIdHlRV1kK7+bAIeLQRa+GbFGE
            UVdn4GS4+IT3/Wkiro3+BSq2Dx7kXjFWG41f6fq6J7/ZvvMyJ3U9wQywn/GK4F0w
            Jizqfw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvT+ITNOzjlDdcTk9kdYLrGYd0EJw6kMr6Ynw9165wR sander@nixos-laptop
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHZpQ3Y3dyBVcFNX
            WkgvOEdFOU50WHhQOTd5bFhaMzVtOExsTUZlSUpSY3E5UGk4K25NClQyZmlPM1pT
            dmVPbVVWSFpFMDBjcDBPbmcrdXpjVXJpS21SYlk2YjZ2eHMKLS0tIFpVMXU3NzZE
            eDlyc3JFRktvSEhORXB5VEZzdDluUU44QnVZVkxrRm03QjQKYOf5uuXCCHLGjOPp
            nJfjzaQ4v5yEDNz9AhXDzuYJqgjTYSOGq/FCpLBdHY6SAnjB6ZCh97ycKXKEjou+
            7aUvBQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGhMesnzIJ89Ic38a3cOFUtiqE/No4FRFkhX+IqIIO3S sander@nixos
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IElVbEhTQSByeVFV
            dFpSYXROYUd3MGRoM2hYUlI0akJhWDBUUjlyM3Bsam5wbDBnWjE0ClRMak9jeDR2
            bmNzeVhHSVROcENENnhONHJpZmJSVTRxVVhWYjZBUmVqbE0KLS0tIHNNcDBzNzVB
            d2M1T3kwTlBjV3BNcTVpZGhXWGRMTHBRaDFZUFBGL2NmcE0KOqZr0+SQsc0Mz9ul
            OhXBcEO9U5yvLHoju9ZGTRoz0/gah65WNOxHFC+0+pFxRZsD+dgfPwkPyCnpPKr+
            wZ9mTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFHe3wCRa3OBsJZJsnXgDDbWaIB18hq0RKUzU1eGqoco slysa@asus-proart
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFBtM1RTUSBQT3J6
            N2xueGZpaEJqU0RXZkxXc0F5dDZod2E4dFhwQTVFM2ZETGxTWHpnCit1VG4zSjZs
            T3R4YndlOCt3WGNScTZReDlEYmJyNjJPNFBwWnhaTnc3MDQKLS0tIG5SRHo1VTFN
            ZXZheUdsUGdjRHVDVXBFaGNlWjVaUkFoMzc1Z09lUGdKQVUKLlHk8+Ye0O2YPol9
            dSQTzSgvrmf8C5WCvBaCEhOX2nzsQRb8CT6P5cjfK6rdKDTfInGFtTWE8nYOhV9k
            0fH7mw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB3+7P7YnvA6ghkemNkLLwoFZL/oTBLUOIz8K5SyQwS6 slysa@desktop
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ZWFEK0ljSm91NTkwR0xa
            TkMrNzBPWmRjVXhLQWZLWC95b09qNVZSRmtvCk9FbTF0YlJkbHU2WjVzSXlmT1ZJ
            UFU2NVVOUmFJWTIvTnR4UHR6ejNsb3cKLS0tIGlZL2VuaEFaRjVWdENJaGVYaVhv
            YkNvZGVYd1pnV0xKRUpQem5RY2JvZDQKkUhB7QO36ZdEJ6u9ZZUnl7p+HQ0rIblX
            xWDBrfNJFtv/UIdSnaek2zPpfb0htEC1C/bqaRZjmHmuAtESc5Yg9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age185wsded9nj5vsw58saezfj8wekkftmpsrhv9cd05ep3k5vap8ckqc9epjn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG1XOCttdyAwUUcw
            c2diWkkrNitYNURrQkdmc1JrV3V3QlpMZEJQenNoa0hTQ01kTkQ4Cmc4Tm1VL2Jm
            WnN5Z1FFWmxoQ29oLzdWdDc5bVJ1dXgrZUZFeUJwTnpybncKLS0tIGZCbWlBZWx6
            MHVNV0ZlQ2ZaRVJ0QWE3eGhlL0M2akwzSzlDVzg5MzBxbTQKzECSQTeAySHk7/vd
            X4x7hO60HMb1UlVhmEfczTXeFQqNHuRILkAFsOPGyqhZoRPdltrKgjnDgj1uJ1HQ
            T/a2Fg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL031Q1Dd6yu310sGwE4++BdJIad4gApbWlsPpMI8Mcx sander@linux
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDEyU043QSB1YUoy
            NDJTWEZrZjlzV0c3MXFSMmVRVmc3Yms0MlVxdFpoTFpUdWNBeGx3Cmx0TTlhNDl5
            RGRkRVpkTlo5VUxHNjFxQXJyTkI3cFlUSjhRYk9tVUdTckUKLS0tIFgyd24vSE05
            RWxBQ2lvWjB1Y3ZRTk4rM2hvUzJTdyszRjQ1SlRGaldDL3MKTUlpA8869AXA+oG7
            lfE8wnOx0b4ujHNqgo1KseWbh+/Z0ZfugN4qqJm/YNNAv0i0olKNvBydZOR+8bhB
            FABYvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPXFrU1bBLmiCk6/kDtrY8hBwZH1G3aLo8w/5psKz6rz sanlys@nixos
    lastmodified: "2026-07-31T10:52:12Z"
    mac: ENC[AES256_GCM,data:NhtgVNPM/kIuNzM7EEeQ+gqowxbpQFF95xI6fyK84zAf18w6SiW1tvyFBVp6euZBZzzumygWPA1xv2mcH1NdIQE+xtZSJ0BQ3AuOL5hDjxqVY0Iv7k1qsIINpJ+bHlemYDJEWNoru0cgPEnLb6uvKawL24wvCZIP+bZVSFI8TEY=,iv:7E66LiOOjeiqE9rCWE32xV1xSOGNxT/2cZjbajP/aLo=,tag:WsyIJgUbBGRwhWBb2cttMA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
