apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-ingresses
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/Sanlys/kubernetes.git
    targetRevision: main
    path: cluster/prod/apps/grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated: { prune: true, selfHeal: true }
