apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: windows11-vm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Sanlys/kubernetes.git
    targetRevision: main
    path: cluster/prod/apps/windows11-vm
    directory:
      exclude: "app.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: windows11-vm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
