apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filestash-data
  namespace: filestash
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block-ssd
  resources:
    requests:
      storage: 2Gi
