apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-local-storage
  namespace: argocd
spec:
  project: default
  source:
    # Inline Kustomization block
    kustomize:
      inline:
        apiVersion: kustomize.config.k8s.io/v1beta1
        kind: Kustomization
        metadata:
          name: cnpg-local-provisioner
        resources:
          - https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml

        patches:
          ###########################################################
          # Patch 1: Configure base path for persistent volumes
          ###########################################################
          - target:
              kind: ConfigMap
              name: local-path-config
            patch: |
              - op: replace
                path: /data/config.json
                value: |
                  {
                    "nodePathMap":[
                      {
                        "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                        "paths":["/var/mnt/local-path-provisioner"]
                      }
                    ]
                  }

          ###########################################################
          # Patch 2: Rename the StorageClass + configure behavior
          ###########################################################
          - target:
              kind: StorageClass
              name: local-path
            patch: |
              - op: replace
                path: /metadata/name
                value: cnpg-local
              - op: replace
                path: /reclaimPolicy
                value: Retain
              - op: add
                path: /volumeBindingMode
                value: WaitForFirstConsumer
              - op: add
                path: /allowVolumeExpansion
                value: false

          ###########################################################
          # Patch 3: Restrict Daemon to only cnpg-storage=true nodes
          ###########################################################
          - target:
              kind: Deployment
              name: local-path-provisioner
            patch: |
              - op: add
                path: /spec/template/spec/nodeSelector
                value:
                  cnpg-storage: "true"

          ###########################################################
          # Patch 4: Ensure namespace allows privileged ops
          ###########################################################
          - target:
              kind: Namespace
              name: local-path-storage
            patch: |
              - op: add
                path: /metadata/labels/pod-security.kubernetes.io~1enforce
                value: privileged

  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

