apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-local-storage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: local-path-storage
    server: https://kubernetes.default.svc
  source:
    repoURL: github.com/rancher/local-path-provisioner/deploy?ref=v0.0.34
    targetRevision: master          # or a tag like v0.0.34 if you prefer
    path: deploy                    # contains local-path-storage.yaml
    kustomize:
      patches:
        ###########################################################
        # 1) Set base path for volumes to your Talos user volume
        ###########################################################
        - target:
            kind: ConfigMap
            name: local-path-config
          patch: |-
            - op: replace
              path: /data/config.json
              value: |
                {
                  "nodePathMap":[
                    {
                      "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                      "paths":["/var/mnt/local-path-provisioner"]
                    }
                  ]
                }

        ###########################################################
        # 2) Rename StorageClass to "cnpg-local" and tune behavior
        ###########################################################
        - target:
            kind: StorageClass
            name: local-path
          patch: |-
            - op: replace
              path: /metadata/name
              value: cnpg-local
            - op: replace
              path: /reclaimPolicy
              value: Retain
            - op: add
              path: /volumeBindingMode
              value: WaitForFirstConsumer
            - op: add
              path: /allowVolumeExpansion
              value: false

        ###########################################################
        # 3) Run provisioner only on cnpg-storage=true nodes
        ###########################################################
        - target:
            kind: Deployment
            name: local-path-provisioner
          patch: |-
            - op: add
              path: /spec/template/spec/nodeSelector
              value:
                cnpg-storage: "true"

        ###########################################################
        # 4) Allow privileged pods in this namespace (for hostPath)
        ###########################################################
        - target:
            kind: Namespace
            name: local-path-storage
          patch: |-
            - op: add
              path: /metadata/labels/pod-security.kubernetes.io~1enforce
              value: privileged
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

