apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-lb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Sanlys/kubernetes.git
    targetRevision: main
    path: cluster/prod/apps/postgres-lb
    directory:
      exclude: "app.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
