---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-paper-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block-ssd
  resources:
    requests:
      storage: 40Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-paper
  labels:
    app: mc-paper
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mc-paper
  template:
    metadata:
      labels:
        app: mc-paper
    spec:
      securityContext:
        fsGroup: 1000
      nodeSelector:
        kubernetes.io/hostname: talos-puf-79s # Fast node
      containers:
        - name: minecraft
          image: itzg/minecraft-server:java25-jdk@sha256:2180e3f66b94a69c4b2b96f300f00487de6d1a7aff0014445a4552c9fa50539c
          imagePullPolicy: IfNotPresent
          env:
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: "PAPER"
            - name: VERSION
              value: "1.21.10"
            - name: MOTD
              value: "Daur's stream server"

            - name: MEMORY
              value: "6G"

              # If level is changed, new world is generated. Seed is applied only when level is changed
            - name: LEVEL
              value: "daur-stream-world-3"
            - name: SEED
              value: ""

            - name: ONLINE_MODE
              value: "TRUE"
            - name: USE_AIKAR_FLAGS
              value: "true"
            - name: ENABLE_RCON
              value: "true"
            - name: RCON_PASSWORD
              value: "supersecret"
            - name: OVERRIDE_SERVER_PROPERTIES
              value: "true"

            - name: MAX_PLAYERS
              value: "100"
            - name: ENABLE_WHITELIST
              value: "false"
            - name: SPAWN_PROTECTION
              value: "0"
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    # Warn players
                    rcon-cli --password "$RCON_PASSWORD" "say Server will be restarting in 10 seconds!"
                    sleep 10
                    rcon-cli --password "$RCON_PASSWORD" "say Restarting..."
                    sleep 2
                    # Kick everyone
                    rcon-cli --password "$RCON_PASSWORD" "kick @a Server is restarting, please rejoin"

                    sleep 3
          ports:
            - containerPort: 25565
              name: mc
          volumeMounts:
            - name: mc-data
              mountPath: /data
          resources:
            requests:
              cpu: "500m"
              memory: "6Gi"
            limits:
              cpu: "2"
              memory: "8Gi"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          # Simple liveness/readiness so kube doesn't flap it too eagerly
          livenessProbe:
            tcpSocket:
              port: mc
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: mc
            initialDelaySeconds: 30
            periodSeconds: 10
        - name: sftp
          image: atmoz/sftp:latest
          args: ["minecraft:minecraft:1000:1000"]
          ports:
            - containerPort: 22
              name: sftp
          volumeMounts:
            - name: mc-data
              mountPath: /home/minecraft/upload
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          securityContext:
            runAsUser: 0
            runAsGroup: 0
      volumes:
        - name: mc-data
          persistentVolumeClaim:
            claimName: mc-paper-data
      # Helpful with Ceph RBD so it can chown the volume
---
apiVersion: v1
kind: Service
metadata:
  name: mc-paper
  labels:
    app: mc-paper
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.6.222
  selector:
    app: mc-paper
  ports:
    - name: mc
      port: 25565
      targetPort: 25565
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mc-paper-sftp
  labels:
    app: mc-paper
spec:
  type: LoadBalancer
  selector:
    app: mc-paper
  ports:
    - name: sftp
      port: 22
      targetPort: 22
      protocol: TCP