apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-data
  namespace: actual
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block-ssd
  resources:
    requests:
      storage: 5Gi
