apiVersion: batch/v1
kind: CronJob
metadata:
  name: restic-backup
  namespace: syncthing
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    app: syncthing
                topologyKey: kubernetes.io/hostname
          containers:
          - name: restic
            image: restic/restic:0.19.1@sha256:136600b6ff6843d61d355f7f71f460a166429f35de6fd11b568fece3c9a4d510
            args:
            - backup
            - /data
            - --cache-dir
            - /cache
            - --host
            - syncthing
            envFrom:
            - secretRef:
                name: restic-credentials
            volumeMounts:
            - name: syncthing-data
              mountPath: /data
              readOnly: true
            - name: cache
              mountPath: /cache
          volumes:
          - name: syncthing-data
            persistentVolumeClaim:
              claimName: syncthing-pvc
          - name: cache
            persistentVolumeClaim:
              claimName: restic-cache
          restartPolicy: OnFailure
