apiVersion: batch/v1
kind: CronJob
metadata:
  name: restic-backup
  namespace: syncthing
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: restic
            image: restic/restic:0.18.1@sha256:39d9072fb5651c80d75c7a811612eb60b4c06b32ffe87c2e9f3c7222e1797e76
            args:
            - backup
            - /data
            - --cache-dir
            - /cache
            - --host
            - syncthing
            envFrom:
            - secretRef:
                name: restic-credentials
            volumeMounts:
            - name: syncthing-data
              mountPath: /data
              readOnly: true
            - name: cache
              mountPath: /cache
          volumes:
          - name: syncthing-data
            persistentVolumeClaim:
              claimName: syncthing-pvc
          - name: cache
            persistentVolumeClaim:
              claimName: restic-cache
          restartPolicy: OnFailure
