apiVersion: batch/v1
kind: CronJob
metadata:
  name: restic-prune
  namespace: syncthing
spec:
  schedule: "0 3 * * 0"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: restic
            image: restic/restic:0.18.0@sha256:4cf4a61ef9786f4de53e9de8c8f5c040f33830eb0a10bf3d614410ee2fcb6120
            args:
            - forget
            - --keep-hourly=24
            - --keep-daily=7
            - --keep-weekly=4
            - --keep-monthly=12
            - --keep-yearly=unlimited
            - --prune
            envFrom:
            - secretRef:
                name: restic-credentials
          restartPolicy: OnFailure
