apiVersion: batch/v1
kind: CronJob
metadata:
  name: restic-prune
  namespace: syncthing
spec:
  schedule: "0 3 * * 0"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: restic
            image: restic/restic:0.19.0@sha256:7f44e0057b82348597568ea209360762d0b38f8e1dbc8ad859661ac1055e45f2
            args:
            - forget
            - --keep-hourly=24
            - --keep-daily=7
            - --keep-weekly=4
            - --keep-monthly=12
            - --keep-yearly=unlimited
            - --prune
            envFrom:
            - secretRef:
                name: restic-credentials
          restartPolicy: OnFailure
