apiVersion: batch/v1
kind: CronJob
metadata:
  name: restic-prune
  namespace: syncthing
spec:
  schedule: "0 3 * * 0"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: restic
            image: restic/restic:0.18.1@sha256:39d9072fb5651c80d75c7a811612eb60b4c06b32ffe87c2e9f3c7222e1797e76
            args:
            - forget
            - --keep-hourly=24
            - --keep-daily=7
            - --keep-weekly=4
            - --keep-monthly=12
            - --keep-yearly=unlimited
            - --prune
            envFrom:
            - secretRef:
                name: restic-credentials
          restartPolicy: OnFailure
