apiVersion: ENC[AES256_GCM,data:sk0=,iv:GmUwfe0Wvg14LDijrlGeT/D78exzop1C0n+1r/YbVHo=,tag:+Ite6y0J0mUdPt8Az5XHKw==,type:str]
kind: ENC[AES256_GCM,data:dEhcnNE5,iv:3G+zcRMDh/2CdHJdcF9rL5mQLEc7BDGmovhFZYkpV+M=,tag:bUfIpuNIo4Xcfa8a4Om/eQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ImJOkxy/58bLwoTKCnjY8yaF,iv:DjNEaRMDV/dWP4hCfLhoEpKlrNuRhSDTUYTjp1+dedI=,tag:JKPAQYEoGMIt6p1IuPMXtg==,type:str]
    namespace: ENC[AES256_GCM,data:mleeAXmM9SWj,iv:Ivo71SyUsHJ8x+oMFOQFBIYfipvfvewgAXP1Abf0UoQ=,tag:DHIqqbes51PhTG6fATRuEQ==,type:str]
stringData:
    AWS_DEfAULT_REGION: ENC[AES256_GCM,data:qgM=,iv:6mPFkgReO4RAob6geBVZwyCDWxMTjEZBt9vambrD4f4=,tag:VDsVrC++UT5mgKt2krkfYQ==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:7UucIyQ0REkyPD2IDK4Qf63XI9pfuijTVQXnosDjQIMDe0yrBME5Pw==,iv:YHZQRPhO4G12xuN0gbeS9HnPt+DwW4v0F1DsyRSo72A=,tag:2nhjb3N1PdpH5rdyGzwBEQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:N3r10PHwfOkDVkqzK2bPwFqw3rY=,iv:D388tdYlDxeHnLUEwXALEj6wi4rN077bRNExzkbLuv8=,tag:zVYl55QU2qNJLkQS3kY7kQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:wadHiXjVLhehKpfIsWBevQxMLtDUEk1hwMYSV/HOsBtPV2/gK1SHwg==,iv:9nGTZGcHOt3VCXFYr4i6JDDg6bY4rB98chxTQGTVWF8=,tag:EHRXduMPq9z0muoDjqGAtw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:nZhLaOrWZcbT1lrumABL9hQpdOrnwCmWFjF6RFdNbdE=,iv:jzNfwkKGhgZzpl8wMCYmTkkP4V5mgmOVsKrWgv4Buhw=,tag:iR9RWyo+IrugjpVO741aUw==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvT+ITNOzjlDdcTk9kdYLrGYd0EJw6kMr6Ynw9165wR sander@nixos-laptop
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE9hRWxSdyBOL0Ri
            MEJIZVpQa2UyYm93bEZmMHdIOUF5UCtNdXdqTlQ5WjYvUHZWNFRvClYxZGNQNUhj
            cjJKRFRWaU5ZdDNuOGFhMzJsQ3ZQMjNnQ29rcnpxbXd4MWMKLS0tIGRyM2dwL2hw
            bElZcW9PNFoxT3lGdXVGYmcreFZ5VzB5OHFIUTl1VEVlaDAK2jB++A5WSQlUIknt
            SW6hTNWzYUj4IIRVmXY+wAWjBIVSJs2UxzZBgcVVlkR5x0etmfUdIBY5w0Ap1KJ6
            AJmyfg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGhMesnzIJ89Ic38a3cOFUtiqE/No4FRFkhX+IqIIO3S sander@nixos
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHZpQ3Y3dyBsOTRM
            enB6RTVBa2J5SmZXYWYrNGUreEhCMWxvczNwd0ZBeFhsVHhHS1YwCnBhRkRpUVF2
            UXI2aTJnMkg3MDBHL1pIVVpzZDBnM3hxcnZpUi93ZmRSWTQKLS0tIFloVmlDSlhp
            c0M3TS9WcTRIeC9IRmROZ295QXBERW9KVGZoVndpdUxkS0UKlT4LA/DIVB63WTPE
            IVnVrurjxi0wUpg0MfNttXHmySerXLfUusPUcBLz+lQErBnzI9hGRxY4syN1mMCT
            Lryhzg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFHe3wCRa3OBsJZJsnXgDDbWaIB18hq0RKUzU1eGqoco slysa@asus-proart
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IElVbEhTQSBiQ21r
            eVNqWTdVamxJNEVVL3RzSXhIRDRVMkdMdjFVK09Qc0R5S1UwdGx3CkFuRXl5TjRq
            alZJb01zdXpuWTVoODB0RU9yZ0lNTDJVUzE3NGpxVDNycEEKLS0tIDRUVU5aSXBB
            NlNPeWJXS2JFekxxK3oyVnA0YWt0VGxPbWRqRE5SMWFwUGsKJkKop/Grx+sgDQok
            iOEJ9E1uaoRuky9yR8GTbIu0OAU4uLnqSJnTwrP1N7t69FTt7XkAjyVo/fO8noms
            uFTHJA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB3+7P7YnvA6ghkemNkLLwoFZL/oTBLUOIz8K5SyQwS6 slysa@desktop
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFBtM1RTUSA1WU9p
            bVhSNTNORkE4Y3RHTkpSQXBwUTJYSDkveVFlTFlsbmVsdnNSakJZCnVCSjMyNkFU
            NkpCWis3Z2FuM3djVlpQQzUzdmVwVDZtTmR4bzdkVDRuVTAKLS0tIGgveFlVYkcx
            ajhUUU5rL1hvRWUySWZXN3liZG5zM1ZCeGxwa3FSdE1JcW8KOmbHeuKVJtgMxIxv
            wj2+jiLlpbDbC3uRSaZGlbDLHCiHjXYZXTwymUGj8je1RxxFYxb7bFlPGvlFvMJz
            D1Z8XA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age185wsded9nj5vsw58saezfj8wekkftmpsrhv9cd05ep3k5vap8ckqc9epjn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NWlXVWt1WFA1cGcvVm9v
            Mk5TZU1xYko5bWFHVHF4WElnMkhmZmF2bHhFClduRkJxUXNoc0o1c1c1ZFI5emFy
            SElxUktXNnh3TWxWM2ttcEpZZ1hvR2sKLS0tIEcwUjUwVHN2K2RUcXZuTVFxYytW
            Q3NZMERKaWl6ZllYNFBkVnRmbUhhS3cKlyT//wutxWF+/uNVJ24nlb4iqSYzQckp
            837U4HaLIcVkMUupqfpsq80hPsRhEgcFonQYLFR7ws+PK6ySejkyjA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL031Q1Dd6yu310sGwE4++BdJIad4gApbWlsPpMI8Mcx sander@linux
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG1XOCttdyBLWHhI
            d2I5K0tqeGJ0UHNlOG1yeFFHSDhnNFRZdU1OeUVRWjZJeS90K0ZnCjJZMWNSdW9G
            cThDcTFjdW5EYktVS211Q2RLNWtja0NjTTFmdkRIY0ZVQkEKLS0tIFd4MGdOZWVJ
            TlNmUDNKTVB0TisxeXF5dFVVRnV5anJ2eTl6ZWRUNk4yQlkKTgZBxvKzhaVvlQBU
            FQtFbDtoAVIuzInWLPbRNtzgWErNMy6NIP+MwhB2W8+bvoWql2DGQmSxdMswsiP2
            KCTFjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T01:37:57Z"
    mac: ENC[AES256_GCM,data:S5YLELqqEPGOMRY3Nb6JyJNSB7Em1df9VDGlusMs3Jt7XfuQO0CkrW+iI5uQeVAwHzqlPnLsLrncffPaSF4+ln+cEPPM8G0IQkKrPnQFx4lyzC4CbihWMMhjyUKjj0/n74AyQCo/YbqYoZpQaapjLPEl8fY1Vf4zcmWyPo07VpY=,iv:Fk6ZL4zCJ59b1YbDVH++h9GjlaDdmc1GEQaJtKwbVcY=,tag:u4GSZ07Ea0C2gVTq5/bScw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
