apiVersion: ENC[AES256_GCM,data:sk0=,iv:GmUwfe0Wvg14LDijrlGeT/D78exzop1C0n+1r/YbVHo=,tag:+Ite6y0J0mUdPt8Az5XHKw==,type:str]
kind: ENC[AES256_GCM,data:dEhcnNE5,iv:3G+zcRMDh/2CdHJdcF9rL5mQLEc7BDGmovhFZYkpV+M=,tag:bUfIpuNIo4Xcfa8a4Om/eQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ImJOkxy/58bLwoTKCnjY8yaF,iv:DjNEaRMDV/dWP4hCfLhoEpKlrNuRhSDTUYTjp1+dedI=,tag:JKPAQYEoGMIt6p1IuPMXtg==,type:str]
    namespace: ENC[AES256_GCM,data:mleeAXmM9SWj,iv:Ivo71SyUsHJ8x+oMFOQFBIYfipvfvewgAXP1Abf0UoQ=,tag:DHIqqbes51PhTG6fATRuEQ==,type:str]
stringData:
    AWS_DEfAULT_REGION: ENC[AES256_GCM,data:qgM=,iv:6mPFkgReO4RAob6geBVZwyCDWxMTjEZBt9vambrD4f4=,tag:VDsVrC++UT5mgKt2krkfYQ==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:7UucIyQ0REkyPD2IDK4Qf63XI9pfuijTVQXnosDjQIMDe0yrBME5Pw==,iv:YHZQRPhO4G12xuN0gbeS9HnPt+DwW4v0F1DsyRSo72A=,tag:2nhjb3N1PdpH5rdyGzwBEQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:N3r10PHwfOkDVkqzK2bPwFqw3rY=,iv:D388tdYlDxeHnLUEwXALEj6wi4rN077bRNExzkbLuv8=,tag:zVYl55QU2qNJLkQS3kY7kQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:wadHiXjVLhehKpfIsWBevQxMLtDUEk1hwMYSV/HOsBtPV2/gK1SHwg==,iv:9nGTZGcHOt3VCXFYr4i6JDDg6bY4rB98chxTQGTVWF8=,tag:EHRXduMPq9z0muoDjqGAtw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:nZhLaOrWZcbT1lrumABL9hQpdOrnwCmWFjF6RFdNbdE=,iv:jzNfwkKGhgZzpl8wMCYmTkkP4V5mgmOVsKrWgv4Buhw=,tag:iR9RWyo+IrugjpVO741aUw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE9hRWxSdyBnYlJk
            ZWtieTd6Vk5HbUp2ZjZkVFFPMmRiYngwTWh4QkIwa2ZsVlhWSzNFClpxTTJObXRX
            TTQ1RTczNmtDS040UEVieUhmS3NJTWYwS0hHeXFvQ01QRmcKLS0tIGV0c1d2MEpJ
            MHVyZUhHSXB0dUlCbnNXVE1BNW5JTGFlbDNyVnp1ejFwbmsKyC5wYe7v62DSaUAC
            yq0hHVhdu8Gu3BEV4lwDiizkbpiDYAFLxTKiJN09YSMl+bqMkaH9Mm7HMf6/5ELM
            Jcoq9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvT+ITNOzjlDdcTk9kdYLrGYd0EJw6kMr6Ynw9165wR sander@nixos-laptop
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHZpQ3Y3dyBrZm5o
            RHRWWi9jTnpxdWhBWncwOG9FSFEyU2JCSnEzMDZpczRYQ0tLL2pRCnpHdEtscEFi
            TS9UN3hFMVk0dHZPajRRQWdmR3N1Vk56b2hTQ1BVT1FPOXMKLS0tIFFqSEN6bXZj
            N01hZnU5ZUF5dHd0VFNkV0Z0UHlGTmxqRnh2emNUS1hCQjQKwrLNnfXUzAAlO9Vl
            bQVs9oYhAxR3l5/dw6OQdD7jdqatOpK2PSabJRU+aXxe7xInmKGPafvsKLCBfWKg
            0YVtQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGhMesnzIJ89Ic38a3cOFUtiqE/No4FRFkhX+IqIIO3S sander@nixos
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IElVbEhTQSBuL3BE
            Q1RERkRXYm1XMXlNdUovWVZMZWZqOEtFL2FuUlNOZTZVL2hDeDBFCklEM29taEFO
            NmNuWkFXWk84cTNoWVMxRENtOFd1cVhrNWpxVXl6KzBmY3MKLS0tIGdnTWJmMUhI
            amJ3NzB5V2w4RWpkTXVudGRuUndHNm5BeDZMRVRPL2RPOFUKEayhG5YqzsOTQSA1
            ViwkTSE2y1HVQI1XjvmlU63Ip5U0Koz/B6qzsUsSbC5lzFllj0QJSjzdCULHwAGA
            yhLXgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFHe3wCRa3OBsJZJsnXgDDbWaIB18hq0RKUzU1eGqoco slysa@asus-proart
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFBtM1RTUSBrU1RY
            MWN4c2hYMEZGYjNUUTNHWURsQjkxdnQ3d2NySUZ2TWRiaXk0a1dvCkEyc2ZnVXZY
            VEVCOFRqR043VzV5RXY4Y1ZMMjNOSG9RWVg5czdmUFNxaU0KLS0tIDI2U0xNWEtR
            TVlSMERNVnVrMEJheW5QTlMvT3JDaVdkWFJ6Z0w0bHhxa2cK8T9BPiTIJjB1+l6W
            IRJOOCHXvl8bhEPNg4IhIDmVtfdf4JHIRN3j5cMlnECVzqzOsMfVXZGGBmMCOsvr
            lGkpvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB3+7P7YnvA6ghkemNkLLwoFZL/oTBLUOIz8K5SyQwS6 slysa@desktop
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bE5NeEdCUzdSeTFieHI3
            MDcra3dwL2hNSndDc0EzSDNBcm9KVElhcUY4CmI0a1k1Uy8zSTlieitieGNLcTha
            SisvRllxQVVpZGpIYU1MZXhmR0toTFUKLS0tIGFVemtHd1IzcEdaNXo1N2pQTm9C
            Z1BOZlpPUDdlYVNkWCtaSE8zY1dPQnMKuioFryf7VvCSYk7N5PeNI02khLdVBkRh
            bY99InApyVEvQwGcODqPPNPp7r/1kA723mv3xn6p83VgwyFFi7mYoQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age185wsded9nj5vsw58saezfj8wekkftmpsrhv9cd05ep3k5vap8ckqc9epjn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG1XOCttdyBFbEZV
            cTI0SWF1YURQRmxMWTR1dUNVaDllL1AySXFjaElRRTF5Q2VLSHkwCjd3NE9CT01o
            dnJ4TkUxYVZLa0lGbEVwT0lkTGRhWlZOQTI2diswLzZQc00KLS0tIHo4bjAveWZ6
            UC9UejhGU0tHaXZxZW1GeEJzaE04NTRDVk52MDFoN3diS2cKiLw8k6oMP644qPV3
            lr6C4FOJ1YWBl9d21YEwzrKJNOz43wRomNDuxVDMYFGltW8YL4vbclBTw9w1dTSc
            6dH5vQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL031Q1Dd6yu310sGwE4++BdJIad4gApbWlsPpMI8Mcx sander@linux
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDEyU043QSAvQnh3
            WVZpYWx2OHRiMlA5b0t2NklVbEFFSzdKNnFtcm5zNjlHVEdqZDNBCnRaOGVVeTdu
            SFpoRzl3cUdSM2twdThBYUZkUHg3M2s0aGxQV1UwQ3FacjgKLS0tIFZzSEZrYlZU
            K1hKUFZic1VoRXZMZGxpVUt1NUROZXo2enBDTi9ScUhJSTgKeMXSdaxNRuoDoJl2
            EFvbzX+LjstkBysmJ5PYMFGxY0RD8ccDSIi4BW62368d88x1BQvAXsaywUpNH/tS
            E9pBag==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPXFrU1bBLmiCk6/kDtrY8hBwZH1G3aLo8w/5psKz6rz sanlys@nixos
    lastmodified: "2026-03-27T01:37:57Z"
    mac: ENC[AES256_GCM,data:S5YLELqqEPGOMRY3Nb6JyJNSB7Em1df9VDGlusMs3Jt7XfuQO0CkrW+iI5uQeVAwHzqlPnLsLrncffPaSF4+ln+cEPPM8G0IQkKrPnQFx4lyzC4CbihWMMhjyUKjj0/n74AyQCo/YbqYoZpQaapjLPEl8fY1Vf4zcmWyPo07VpY=,iv:Fk6ZL4zCJ59b1YbDVH++h9GjlaDdmc1GEQaJtKwbVcY=,tag:u4GSZ07Ea0C2gVTq5/bScw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
