// Package samba renders smb.conf from the gateway config and keeps Samba's
// user database in sync with it.
package samba

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path"
	"sort"
	"strings"

	"github.com/Sanlys/kubernetes/services/smb-gateway/internal/config"
)

// Every share's file operations run as this one unix account; who may do
// what is decided by Samba per share (valid users / write list), since the
// rclone/restic filesystems underneath have no per-user permissions.
const (
	DataUser = "smbdata"
	DataUID  = 1000
	DataGID  = 1000
)

// Junk that clients sprinkle everywhere and that has no business being
// uploaded to a bucket, plus Syncthing's internals.
var defaultVeto = []string{
	".DS_Store", "Thumbs.db", "desktop.ini", "$RECYCLE.BIN",
	".stfolder", ".stignore", ".syncthing.*.tmp", "~syncthing~*.tmp",
}

// Render produces smb.conf. treeRoot is where the mount tree lives on disk.
// readOnly reports whether a share path ends up on a read-only mount.
func Render(c *config.Config, treeRoot string, readOnly func(sharePath string) bool) string {
	var b bytes.Buffer
	w := func(k, v string) { fmt.Fprintf(&b, "   %s = %s\n", k, v) }

	b.WriteString("# Generated by smb-gateway from its config file - do not edit.\n[global]\n")
	w("server role", "standalone server")
	w("netbios name", strings.ToUpper(c.Server.Name))
	w("workgroup", c.Server.Workgroup)
	w("server string", c.Server.Description)
	w("security", "user")
	w("passdb backend", "tdbsam")
	w("map to guest", "never")
	w("restrict anonymous", "2")
	w("server min protocol", c.Server.MinProtocol)
	w("smb ports", "445")
	w("disable netbios", "yes")
	w("dns proxy", "no")
	w("load printers", "no")
	w("printing", "bsd")
	w("printcap name", "/dev/null")
	w("disable spoolss", "yes")
	w("log level", fmt.Sprint(c.Server.LogLevel))
	w("logging", "stdout")
	// The filesystems underneath are rclone (S3/SFTP) and restic: no
	// xattrs, no ACLs, no byte-range locks, and every smbd process sees the
	// same mount, so Samba's own (tdb) locking is authoritative.
	w("ea support", "no")
	w("store dos attributes", "no")
	w("map archive", "no")
	w("map hidden", "no")
	w("map system", "no")
	w("map readonly", "no")
	w("nt acl support", "no")
	w("inherit acls", "no")
	w("kernel oplocks", "no")
	w("kernel share modes", "no")
	w("posix locking", "no")
	w("strict locking", "no")
	w("strict sync", "no")
	w("sync always", "no")
	// restic's mount uses symlinks (hosts/<host>/latest), and snapshots may
	// contain symlinks pointing anywhere on the backed-up host: follow them
	// only while they stay inside the share.
	w("follow symlinks", "yes")
	w("wide links", "no")
	// S3 keys (and Syncthing files from Linux peers) may contain characters
	// Windows can't represent. Map them to the private-use code points macOS
	// uses for the same purpose instead of 8.3-mangling the name.
	w("vfs objects", "catia")
	w("catia:mappings", "0x22:0xf020,0x2a:0xf021,0x3a:0xf022,0x3c:0xf023,0x3e:0xf024,0x3f:0xf025,0x5c:0xf026,0x7c:0xf027")
	w("idmap config * : backend", "tdb")
	w("idmap config * : range", "3000-7999")
	w("unix extensions", "no")
	w("smb2 leases", "yes")
	w("aio read size", "1")
	w("aio write size", "1")
	w("use sendfile", "yes")
	w("force user", DataUser)
	w("force group", DataUser)
	w("create mask", "0664")
	w("directory mask", "0775")
	// Clients disconnect cleanly after this long idle; keeps the number of
	// smbd processes (each with open handles into the mounts) bounded.
	w("deadtime", "30")
	keys := sortedKeys(c.Server.ExtraGlobal)
	for _, k := range keys {
		w(k, c.Server.ExtraGlobal[k])
	}

	for _, s := range c.Shares {
		fmt.Fprintf(&b, "\n[%s]\n", s.Name)
		w("path", path.Join(treeRoot, s.Path))
		if s.Comment != "" {
			w("comment", s.Comment)
		}
		browse := s.Browseable == nil || *s.Browseable
		w("browseable", yesNo(browse))
		all := c.ExpandPrincipals(append(append([]string{}, s.Read...), s.Write...))
		writers := c.ExpandPrincipals(s.Write)
		w("valid users", strings.Join(all, " "))
		w("read only", "yes")
		if len(writers) > 0 && !readOnly(s.Path) {
			w("write list", strings.Join(writers, " "))
		}
		w("guest ok", "no")
		veto := append(append([]string{}, defaultVeto...), s.Veto...)
		w("veto files", "/"+strings.Join(veto, "/")+"/")
		w("delete veto files", "yes")
		for _, k := range sortedKeys(s.Extra) {
			w(k, s.Extra[k])
		}
	}
	return b.String()
}

func yesNo(b bool) string {
	if b {
		return "yes"
	}
	return "no"
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// EnsureDataUser creates the unix account all file operations run as.
func EnsureDataUser() error {
	if _, err := lookupUser(DataUser); err == nil {
		return nil
	}
	if err := run("addgroup", "-g", fmt.Sprint(DataGID), DataUser); err != nil && !strings.Contains(err.Error(), "in use") {
		return err
	}
	return run("adduser", "-D", "-H", "-s", "/sbin/nologin", "-u", fmt.Sprint(DataUID), "-G", DataUser, DataUser)
}

// SyncUsers makes Samba's passdb (and the backing unix accounts, which Samba
// requires but which never own any files) match the config exactly.
func SyncUsers(c *config.Config) error {
	want := map[string]string{}
	for _, u := range c.Users {
		want[u.Name] = u.Password
	}
	existing, err := listSambaUsers()
	if err != nil {
		return err
	}
	for _, name := range existing {
		if _, ok := want[name]; !ok {
			if err := run("pdbedit", "-x", "-u", name); err != nil {
				return fmt.Errorf("removing samba user %s: %w", name, err)
			}
		}
	}
	for _, u := range c.Users {
		if _, err := lookupUser(u.Name); err != nil {
			if err := run("adduser", "-D", "-H", "-s", "/sbin/nologin", "-G", DataUser, u.Name); err != nil {
				return fmt.Errorf("creating unix user %s: %w", u.Name, err)
			}
		}
		cmd := exec.Command("smbpasswd", "-s", "-a", u.Name)
		cmd.Stdin = strings.NewReader(u.Password + "\n" + u.Password + "\n")
		if out, err := cmd.CombinedOutput(); err != nil {
			return fmt.Errorf("setting samba password for %s: %v: %s", u.Name, err, out)
		}
	}
	return nil
}

func listSambaUsers() ([]string, error) {
	out, err := exec.Command("pdbedit", "-L").Output()
	if err != nil {
		// Empty passdb on first start.
		return nil, nil
	}
	var names []string
	for _, line := range strings.Split(string(out), "\n") {
		if i := strings.IndexByte(line, ':'); i > 0 {
			names = append(names, line[:i])
		}
	}
	return names, nil
}

func lookupUser(name string) (string, error) {
	data, err := os.ReadFile("/etc/passwd")
	if err != nil {
		return "", err
	}
	for _, line := range strings.Split(string(data), "\n") {
		if strings.HasPrefix(line, name+":") {
			return line, nil
		}
	}
	return "", fmt.Errorf("no such user %s", name)
}

func run(name string, args ...string) error {
	out, err := exec.Command(name, args...).CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s %s: %v: %s", name, strings.Join(args, " "), err, bytes.TrimSpace(out))
	}
	return nil
}
