apiVersion: ENC[AES256_GCM,data:VR8=,iv:OD2SWCUhi7peLnWqeHRxcpGz4S6v/v7HKbLhXpoo/1M=,tag:ZBGbvVzOLasbKIbgm7tThA==,type:str]
kind: ENC[AES256_GCM,data:PEPQJMLm,iv:POMfEc0DT268igv1CmEklzapJTTog9hMK2QHyQPeImo=,tag:vdB4Lk5X77AGFhD17g7dRA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:j7E5okxcAAhg05GbrZRxJRth,iv:j4uxQis74HgVeesTxyx3Nvi9dxNZgnP52QRYJOs42/4=,tag:W49U2tkkj2hEi3RU4KmLdg==,type:str]
    namespace: ENC[AES256_GCM,data:cuiNHthq83uv4g==,iv:9+MWNSRnsSmFnSiWfwkZipPXQXuyFD8FrsOCUprRuUw=,tag:JU5Fo8tEqz5FOSNfyl4IEQ==,type:str]
type: ENC[AES256_GCM,data:dxHwu3Cd,iv:M0su1iunMJiKaXaeYLRda98Zq0gbepDl3cZYhjgm6OM=,tag:6ZZjXXxcsgoXiLMYQK5K8A==,type:str]
stringData:
    DISCORD_WEBHOOK: ENC[AES256_GCM,data:SJu5eMjAWnq/jITDTEdoPMNj5N/kQUymtTxMJ/WY7JlUNG+lTq/NQrMWrOdrhkL86L397oTK8UNGyl2zFlNvS32hSxMgt5Hsw4WOxW3BmBBeUDb64ECKVXWGwfS8ydv0tPHd2cdmZGfHc+sl5/w6fe6KrO94ZK/XsQ==,iv:57/Gv4nCQSRjqjQ/3yUBewcRu1z5TcWYVyXF4FiEHYM=,tag:ovFsRJn+88BUQSfW42Yatg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE9hRWxSdyBzM3Yr
            NzIrcUZKdW1mbmJLQnJEc0VjTjQwWUtVYnZheWhObFZrYlZtNFZzCkxZckQ3SUJS
            cUZTdHdCZnFvVmZPTnoxcGo3UnhRbVJ2N3R5cXJZajNyN0EKLS0tIGpDT0ZTVGRo
            bFd4SEhUYmFCTGxWTFN3VHZweHF2RGk3OG5raFNCZHl4UWcKuFPwUUSVnbRmPRzN
            H9IgU3zLDFNjEY4nxEGpebLTL8SeNXPIkOAhpPMwrvkzOkM7HIcsgwFCoRrp4B8H
            u4ZfhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvT+ITNOzjlDdcTk9kdYLrGYd0EJw6kMr6Ynw9165wR sander@nixos-laptop
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHZpQ3Y3dyBZUXdU
            WGJnb28rMWdVWDVtaXkyOTh0WnBsR1JPRVpsbnduSWdwWlBYTmpzCkh0clFoZnZy
            NFZHYjF6YmpKMzdENEpTUUlaRXZCa1I0VlRhYUhzWk03NlkKLS0tIHAzYWhuNUNj
            b1o2d0FqNXZqdnkvcjh2eGRwOGd1RkhWTUlBTDNRaGNvSTQKNhDpMnpLJjHjXp5B
            HfvCLoKMRZPMl9HdjIyzKt+e3uKKBA1urhcW4Kz8mTwdoc6N1WXcIwz9li6EyAQ5
            Le7cgg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGhMesnzIJ89Ic38a3cOFUtiqE/No4FRFkhX+IqIIO3S sander@nixos
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IElVbEhTQSBMZmtx
            Q0FwMGVsRWNsdDFRRDRDOXRuSVFkNXE4dS83WkdsYUJxSkkwSjIwCjM4SGY4WXZy
            N1JuZnVEUlQ1dUE2L1AyRjByRjZjeWpCcUVUMGd4cWlSTlUKLS0tIEwxMjhEbHRU
            eENPcjZ1UU5KNmpVeUZMOGxlYkxXc2VGU0dwWWxlVVNvdTgKJgVrpiqWkdTDQMA9
            g9iS2gpfySfF5XvLE3ausxjeLwpvxgfcndmrYjcVFfd+a/JQpX9swjmLwpMTuHcR
            bUGtVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFHe3wCRa3OBsJZJsnXgDDbWaIB18hq0RKUzU1eGqoco slysa@asus-proart
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFBtM1RTUSBPbkNI
            U2NLTDA0V3VpV0hQQno0VGhwQ2JKMmt1YU82TWREOHE1UzY1eG5JCk1FUDJyOEUr
            VEQrV1V3Wnh3VHhYR3orUmtXQTVJYXd6WmRSL01TczArbmsKLS0tIHVUNU1NSk5X
            eFl5ZjEzSW1ZU2Z3NVpoTXJXYVpZMUx3cnpOdkxkNFBZVWcK6czRYczp/Yb9RnXs
            RqD0bxK+x5nIYcmgu9q0F/ItXea2iRO+h8nHB2/NHbQSwlndlqsnF0DmXGVAhthB
            Kqg60g==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB3+7P7YnvA6ghkemNkLLwoFZL/oTBLUOIz8K5SyQwS6 slysa@desktop
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdUIvQnBUdE1rUzc5VWJB
            YVB1TzBWd3MxemE3MFJpQkFRbVRKNms0bnlJCnRvL2UrbUJMQVkydzhJTUZ3a1Br
            OWpqYXpqWlhKcitaWXRqNGlQYldKdm8KLS0tIDRycXdYaldRSzB5dEQxSFdiUVd2
            anI3bzlISE5Nak8yeXdPa0NEQ05PWTAKKWpPpe/LIV6TSxgDzLszXn1L9NM9d7JW
            j6VuvIQY+G9xEj0+v43kW7RXPKxA6KkMFksLcrBkJe3qRezsOesFMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age185wsded9nj5vsw58saezfj8wekkftmpsrhv9cd05ep3k5vap8ckqc9epjn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG1XOCttdyA0QklC
            QjkyemlkWm9xRmdoZWVDYjJmZWVMK1VURHpxa2ZrazAzRVVscWhBClpwb3VCMGUr
            UFI4cnkzckI3QzQxLzVUVEc0TkJvNGc3dmszWWMxeDZtTjQKLS0tIEl1OWpHaVlu
            MmpyeERTRmlaRFQvTE93WWtVQzB0c2FQbWtvU1l0NUtlbWsKgpWekQtG0vv2VIq7
            8QfB00h1QmZQoU8GFlj8f4fjCMhVWIhwvW9RM2Z3z9olNvBzNxCDwDLCAE5prq5v
            kef/Sg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL031Q1Dd6yu310sGwE4++BdJIad4gApbWlsPpMI8Mcx sander@linux
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDEyU043QSBDRUxu
            WGtudXhvRE5WbWZIOEhuSnpraWMwRm56MnE2c0E5UjlaYWNvYWhFCncxeXdRdFVp
            VEt0OFRkUEZvVnFjZ1pqYlcxVGJZN1lBc1o0UnNQME1qaUUKLS0tIHVma3dUQUsw
            SkNnRUJPaU91SlNha21CdVh3OGhuSGhyR0IzdCtFYzA4NGMKpxRmKi7wEst0UfuN
            fq/i0ju1GKDHfDRvko6maUDO8Gl6bn5AxSUUa0OKuEavDAvLqDRGyHqhgnr6xEWK
            3qGVsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPXFrU1bBLmiCk6/kDtrY8hBwZH1G3aLo8w/5psKz6rz sanlys@nixos
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdqWWNkdyB1TThX
            aGh2RTJNd0RmbUZCZGxyWlFQMEt1LzgzUjhmUlRDNkFLcnBNN0QwCmI3aVFWWmtN
            SlBncGMxS3dEQ1ZITFVodUlhWHU5THdiVUplVm1tSmF3dFkKLS0tIHNrZmFrc1pG
            bkF0UDNCRnM0SUFzWmRDU2tkdi9CYjczRTQvVjVkNWk3ZkUKLWyH+KuIysW2pSv6
            oYcEoxW6sq/exjO65+nImmaNNWtoY4j5d/ls3GFVs24duX7cRq6N7yX858DOF4TM
            SipEww==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJxVXIN2uJgZC7mU0yZXHkEwp9VPTnlO4pEHVWs/7KXa sanderlysakermoen@Sanders-MacBook-Pro.local
    lastmodified: "2025-09-20T15:12:53Z"
    mac: ENC[AES256_GCM,data:rZQinnLCgqDMn9YUmsgI9gB470s286ZoJty0Kn6eoJ4kRabjQJ1KmaM3zSvDrucHqz44flvy5zDho2tw/0gI2vN5iKoQU1mN3cfDAW9P0JIAwg/60QBXDc/v4kBKSfg5oTq5J0Lw5f+EzAGRO++H/NvMoaywGlncmGstOWDKAu0=,iv:6vOFfgxRhx7KYkHufBsBMQit2MLE6TkyQV2kHAxMFlU=,tag:BLcxjDocHms4lx49xtpZrw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
