apiVersion: ENC[AES256_GCM,data:VR8=,iv:OD2SWCUhi7peLnWqeHRxcpGz4S6v/v7HKbLhXpoo/1M=,tag:ZBGbvVzOLasbKIbgm7tThA==,type:str]
kind: ENC[AES256_GCM,data:PEPQJMLm,iv:POMfEc0DT268igv1CmEklzapJTTog9hMK2QHyQPeImo=,tag:vdB4Lk5X77AGFhD17g7dRA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:j7E5okxcAAhg05GbrZRxJRth,iv:j4uxQis74HgVeesTxyx3Nvi9dxNZgnP52QRYJOs42/4=,tag:W49U2tkkj2hEi3RU4KmLdg==,type:str]
    namespace: ENC[AES256_GCM,data:cuiNHthq83uv4g==,iv:9+MWNSRnsSmFnSiWfwkZipPXQXuyFD8FrsOCUprRuUw=,tag:JU5Fo8tEqz5FOSNfyl4IEQ==,type:str]
type: ENC[AES256_GCM,data:dxHwu3Cd,iv:M0su1iunMJiKaXaeYLRda98Zq0gbepDl3cZYhjgm6OM=,tag:6ZZjXXxcsgoXiLMYQK5K8A==,type:str]
stringData:
    DISCORD_WEBHOOK: ENC[AES256_GCM,data:SJu5eMjAWnq/jITDTEdoPMNj5N/kQUymtTxMJ/WY7JlUNG+lTq/NQrMWrOdrhkL86L397oTK8UNGyl2zFlNvS32hSxMgt5Hsw4WOxW3BmBBeUDb64ECKVXWGwfS8ydv0tPHd2cdmZGfHc+sl5/w6fe6KrO94ZK/XsQ==,iv:57/Gv4nCQSRjqjQ/3yUBewcRu1z5TcWYVyXF4FiEHYM=,tag:ovFsRJn+88BUQSfW42Yatg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE9hRWxSdyBIWWZz
            ZUdnaEorMmI0eWtDSUMwOUZuanBCTFIxeFNSMUI1Ym40NXBoNmxNCjMrV1NjV2Ru
            TVRoYzJhNDFUL2Q4OStUVDczNUFVMEtoK1dCUVRzbEdUTFUKLS0tIE56QnpiU0Fa
            UlFidG5PU2JVR1gyZzNtYVV0WXA2aUlIbEl5R0Z2QWpuK0UKogyGQS6rmQfgMA4c
            uidKaBG6B4dar519/nzSG+W2dajq9UO7eyjSBilYqfV1Z/mHpN/DSx3OG9lQToJD
            6CscdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvT+ITNOzjlDdcTk9kdYLrGYd0EJw6kMr6Ynw9165wR sander@nixos-laptop
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHZpQ3Y3dyBSTkc0
            RzllT0wycnZWZEV5OFU1VmtRTnFRTmpENXE5SjRZM3hxRHNCLzNBCmdnbmVlbFJS
            d2NLUWtMeTAxQmlnU1N3aFFlV3psTTFNTDduei9KM0NDM1UKLS0tIFllNE02UGox
            SjJJWmkxWDduU3VaNWtQbnF3aXJkaUpNQ0hRckZ1T3JUVUkKGd5HNzmFoishMxRx
            4f4tAORDBNQXzT/QevqpvBpYN5vDZI44/On3fYZerHIcYH+8rpEbZRpK0KQSa4dj
            O7mJqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGhMesnzIJ89Ic38a3cOFUtiqE/No4FRFkhX+IqIIO3S sander@nixos
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IElVbEhTQSBGWlc0
            aVZmU1pxd2dTYzBzZ3hHTXJnbTBRYmI3MWx1ZjVFS2w1cmdZSUUwCmRjNC9TdklV
            NHBWY3VYS2RHbEVTYkJleVV0ajl6Tmh3UXA0TGRwbEtpVlUKLS0tIDlad2ovTVN1
            UzZKc0NyN3M1M2IrN2FhRko5b213Z2dTN29jbkFhYmtWc00Ktb2CWhKz5ZreM8fr
            rM9mu5/p77MpkFmokQoquGy/SDehJUkGZ5k2dQxIMeCGNYwfBfux08p+SNLa9KyP
            DQ4WoQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFHe3wCRa3OBsJZJsnXgDDbWaIB18hq0RKUzU1eGqoco slysa@asus-proart
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFBtM1RTUSBDdVhO
            YWJKaVp6NlIxSnplZkZJT2R3RTRBQzhsNnpQVzhZYlMySDltbld3CmNVTC9DV1Nw
            Wk1RQUlpTDFLZmNPMGhaTHExQlphbEY1eTgzcWN6V3VPRUEKLS0tIFNzNUJZWUhl
            U2NxMWNwK2oydXYyTlBzajZLTVk5Z2cwN1p0N3ZTMzA4S2cKUCbjAVLNLjAKlclT
            i9OddCcApxf5bCQ3KrWwFLHcoG6FaKaCjeKoQHFnbosqSDt+Jwy4Xa/zBAlb7/lR
            Acv1tQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB3+7P7YnvA6ghkemNkLLwoFZL/oTBLUOIz8K5SyQwS6 slysa@desktop
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMjRlalcyeVl1K0lEblhY
            QVp5Y0dOME9XZnZJUWRzRlpOWmVORUtXTmo0Ci9EeitrdGZ4SzNWUzZWUHYrQjU0
            WG1TUEVJSXQrWjJjSzZyUndIT1V5YlkKLS0tIDJBQ2Y1QTNwY2FjNkRZTU5HTjRw
            YktGOW5RcURNb3A4bXd5ZXZnU3lneFkKL8v5gMqEzbvLvf6WoopCjV2LSGTESWz3
            33SJt9L1WjBQgZeZ0DT/VGt2/SEwZPfbvUFOxVh3sF7/X+04Mjf5PQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age185wsded9nj5vsw58saezfj8wekkftmpsrhv9cd05ep3k5vap8ckqc9epjn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG1XOCttdyBpc3hE
            cm5MZDhIbHpPOStDejJKaWJyazI1Smg4VlBGTkxlSGdwUjJKaUI0Cm82TDNRRmZX
            bXYyTXlYb2xGNHNpQTIxdnlFUkZZMEVidGYya21uUWVWRFkKLS0tIEM2MW5KZEh3
            VjBCaDFHeXV5K25VSkhLQjhSZnRqblkzNkREOVo2QU1TNTgKIIdlAc5US0asvKJz
            5LtwDHEH3F3xAgCp+6bG8+kflnXuhl+dQo+CGzruy7ksYjlruij4GALAlZ7pnA8F
            syBzOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL031Q1Dd6yu310sGwE4++BdJIad4gApbWlsPpMI8Mcx sander@linux
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDEyU043QSBNaGpo
            NWtualNkK01RaDBJb1RvMktxQit5Ni9NdXVzVlRFTEJkWEgyWHlBCkZiZVJmNGxQ
            WjRsajRUeU9ET0RielNxQS9Zb3dWdkpDeUlLRnltOEVmVE0KLS0tIEt1NVdMRjNr
            OWtQMzVTZmNaRUU0ZXJDVGl6UjhuL3FRcnY0VjZ3bXo0dEUKsEvrrYEryzIA3GFQ
            3b1zpY7VBlwJZnfBFnRPoh6ZhwccscxI7UM3f/aNKIPewUOX7YyYDlSWiwqpXVuI
            E400Ug==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPXFrU1bBLmiCk6/kDtrY8hBwZH1G3aLo8w/5psKz6rz sanlys@nixos
    lastmodified: "2025-09-20T15:12:53Z"
    mac: ENC[AES256_GCM,data:rZQinnLCgqDMn9YUmsgI9gB470s286ZoJty0Kn6eoJ4kRabjQJ1KmaM3zSvDrucHqz44flvy5zDho2tw/0gI2vN5iKoQU1mN3cfDAW9P0JIAwg/60QBXDc/v4kBKSfg5oTq5J0Lw5f+EzAGRO++H/NvMoaywGlncmGstOWDKAu0=,iv:6vOFfgxRhx7KYkHufBsBMQit2MLE6TkyQV2kHAxMFlU=,tag:BLcxjDocHms4lx49xtpZrw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
