apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-privileged
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: privileged-containers
      match:
        resources:
          kinds: ["Pod"]
          namespaceSelector:
            matchExpressions:
              - key: role
                operator: NotIn
                values: ["infra"]
      validate:
        message: "Privileged containers are not allowed"
        pattern:
          spec:
            containers:
              - =(securityContext):
                  =(privileged): "false"
