apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-hostpath
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: hostpath-not-allowed
      match:
        resources:
          kinds: ["Pod"]
          namespaceSelector:
            matchExpressions:
              - key: role
                operator: NotIn
                values: ["infra"]
      validate:
        message: "hostPath volumes are not allowed"
        pattern:
          spec:
            =(volumes):
              - X(hostPath): "null"