apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: gallery-fs
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 2
  dataPools:
    - name: gallery
      failureDomain: host
      replicated:
        size: 2
  preserveFilesystemOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: true
