apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: gallery-fs
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: osd
    replicated:
      size: 1
  dataPools:
    - name: gallery
      failureDomain: osd
      replicated:
        size: 1
  preserveFilesystemOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: true
