apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cilium-agent
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames: ["kube-system"]
  selector:
    matchLabels:
      k8s-app: cilium
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: NotIn
        values: ["hubble"]
  endpoints:
    - targetPort: 9962
      interval: 30s
      scheme: http
      path: /metrics

