apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hubble-metrics
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames: ["kube-system"]
  selector:
    matchLabels:
      k8s-app: cilium
      app.kubernetes.io/name: hubble
  endpoints:
    - port: hubble-metrics
      interval: 30s
      scheme: http
      path: /metrics

