apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cilium-operator
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames: ["kube-system"]
  selector:
    matchLabels:
      io.cilium/app: operator
      name: cilium-operator
  endpoints:
    - targetPort: 9963
      interval: 30s
      scheme: http
      path: /metrics

