apiVersion: ENC[AES256_GCM,data:nZs=,iv:NryJeHS01KmT+VvRxk0kGCv2oEIXCx2frJRa6O/5MFY=,tag:j+q4CoSvhSjuEEhyzWdzdw==,type:str]
kind: ENC[AES256_GCM,data:bZVGdTIX,iv:bjEXwsaookTv3Dtb/NcyOdM2t8d4h9Vhd5tqHdIKN6w=,tag:t1kh3Qq4UpRz4MN/kS42Jg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6ncuOuroHdgWtes=,iv:GHMRJQSDNSkojlnIbDPrbdWCg0Gy4+Q8RdlwoKRy/Gc=,tag:6nXuAFXaomgxoy3uC9UfmQ==,type:str]
    namespace: ENC[AES256_GCM,data:Fkt6aw==,iv:MIaHgdKH7MFknBO+4wwxrThPPayk5nnOC5JpxFTdZ3c=,tag:gOw4u3ptc+9omPSHa5zvFg==,type:str]
type: ENC[AES256_GCM,data:y81gIaHi,iv:RuMse2xyY7y2w6/xgK0knome+EZ4DgDwPOpeyKAoaig=,tag:GjGqeuWcJM9wyYmBLKojjQ==,type:str]
stringData:
    frpc.toml: ENC[AES256_GCM,data:Ic/8KWt6W/cAKHH31VTSPLQLOCKSusJ8Cf2Gw4QJ2SG4Wp4/5zacjMJ0g6FfOzIkqTYqjIoJfHsGKtVDzcsefUlGXw/JngNW/Tp28HS9HShVhWDZMnnefhQSRZmcOJLLHfWwnqCJ2qfy7gnN+ciYybh9GCyvnjGLpACUt0jSiqhAbih/Y6Q1/zwCFVYQ7xkamFS2sRs/F2Cu9VPOE/Mnum1UXJlHDVoyTs3SRogqaDMm/WUeuM4qIOuusVBw0SpUd5vhEIQ/vRdpOTE2sjof1KFoK7OX3TgKhcIIvqC5e+2TuqItyUb4vQgZe4oLMt84GtD5dy23xwWiBdAp/ByXV9tGaqFsYEBO79KZ5FyCWAG8E4ipmF8CPk0N2VNSgcLPN40RavzE+ZPTVfmYoA+d8a3YIOMABHmlGS1zkPUmTL7CSed9m0PqXloWm9qVgySAHwijAPJ03BT3FvYWK3RTeHi10oBKr6qnDckus5IU/xxtw19rJ3ohZ8/DrPqOh8eoJRofJuI8KMiw7tOhTW0bb0aDHYCPClp317QPm2kf5smOmSOgAwnKP5h5RGqFTdcBge0BrSw015ptujHIQltGrwKTIFEg5kqBpbUwPsdwIkfTmDT67VUlscFAkZGFnESLgO00DdWe0q8+bEafCMMPbsLCyAIN2uN3wEXiUeTq+Fk7TgAfEYiYkbCCk2PvfcCqLpCivNrUrT1S0nndujtZmLq9f2rGKJm9C7JeefQtmQqMN0IBvN6eazo9z3S2s4rIlL5HqHe94hqj7bBV0udwpOnrRMyyMxhJhxUugU1QmCSxaCtg4ChyElCbz7hxvi/g3THTefYwy647jhdDzf5cLbr6iak/L480zi56iA+ENUML/UE8DMC3dOrWbjR04JSu3+OitgrnWFq1jt1aEOkoAMJ/UqQN0e1u,iv:efXRyqUsyXsVFXWXoFnCJJdG5tcAVaSA33k2MmixPS4=,tag:NongZuXrNM+GHdeTgcV8zg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE9hRWxSdyBBeitw
            eEl2QkUxQnRPWGM1ZWpTUGQ0ODVjSmxBY2ZGalVXUENiZzJmV2pNClEycmlPUUJz
            ZjIwcDhPSElmdVVmUDRablJNMll0TmtEaitVODl0RW1oRDAKLS0tIHh2ZnlnR1Ar
            Tk04c0ZMTkxudUFVNDNjbEIzc0lyQmZ4YmtNN201UU5VaVEKn0UsCg0gPk2JF1p6
            VWurV2nDUWhISkcOZ8yDkXOA6ZZeTVX1DDrEI7rmFROmxdCH7ThnnypF4dVeJMVG
            xRm3Ag==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvT+ITNOzjlDdcTk9kdYLrGYd0EJw6kMr6Ynw9165wR sander@nixos-laptop
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHZpQ3Y3dyBCQVF1
            QkUxQjFucU4yT2FVRHBLVUROaC95WmRlQVBLaHF6Z2hlbTBncGtVCjU3aUVXSm4y
            YUpJSnZXYzM2ZC80WHBIUlU1YWNackMzQkhqMndwVEwwa2cKLS0tIGJibkRwNmpx
            YWxqYm1pQWZReFVURE9HZnQ4dGdWUjZ1SHNTT2J0a1llbEEKHK0nu54zOaNdUWYd
            jTOnkFa6CL56mX5I56ccsSXH81SUVCIfpUiBgPdjjJzzPriUcMkqCfaXpM6BXSXB
            tIZhOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGhMesnzIJ89Ic38a3cOFUtiqE/No4FRFkhX+IqIIO3S sander@nixos
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IElVbEhTQSBaWkQ3
            MmN3aW5aZGNtWGZaVHhPK0ljSlVOUFdsSmJ2YmZzb0luaThqS25FCkc0dHV5Tng1
            M3VuTS9mK0hPV003Tjh5elFDTC9lU0VkY1Ercit4TnNmeU0KLS0tIGtwREIvcGNu
            bkpvNWE4Sm9PcHZqcytXMncxaFRJdWVsVVMwd2RVRWk5eFkKiw1mQ3bXNjnwITBC
            2188N33cEuC2rtPNUDD+gcNZpvmCxyV5VTl9IPWkC1Q1bbdC6PWCsnpIxejtBx1F
            4tVpGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFHe3wCRa3OBsJZJsnXgDDbWaIB18hq0RKUzU1eGqoco slysa@asus-proart
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFBtM1RTUSB6bEJO
            Uk1nRUc2Z1BnV3ZLa0RwcUlldi8zU2E2NEN3Y3piaEJaTEFOQ3hVCitUeUhvMks5
            dDBaWnFpSHNLSDAydUY5eDlsKzRKOGQ4MWxZZlFscGZNOGsKLS0tIERrVXhGaEJW
            YjFhUXN5a1paanFNZEJ0QVloQUNCbGJLRkplTkVaZ2ZhRzAKrjHrnVOCUISHjHrR
            Z5kDJ/Zr68efUiWz0Z9n4xaCMSJCX72Np1shWMkqkTAPELaeM/zXIIJOTY0OWZVm
            8K21gA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB3+7P7YnvA6ghkemNkLLwoFZL/oTBLUOIz8K5SyQwS6 slysa@desktop
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSUhwdTlXemdMa3k1RG94
            dUJVSDJYNjZMUmo5ZDJZVXV3bC9ZaVlxQXhzCkt4ZmJ1dHJmZU9mREx6d2VXb3Q2
            cE1wc0xQU2xZczNGRGdoVlZjbzdtdkkKLS0tIElaWWMwYmRpc1NVRE1oSUxhTDgw
            T0RsY3ZSR1A3bjV3SFhhNTJlakF2cGsKm4UOM/RL2dlAtF/nae21PiUDzDUJiJ5/
            D2ArV9rEY5fjhX2zv83Tl2ebFlHt5o3T2tRB7rQKXbfsdXN12yCqQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age185wsded9nj5vsw58saezfj8wekkftmpsrhv9cd05ep3k5vap8ckqc9epjn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG1XOCttdyBvTzcz
            V1lsdlBZQkFLQWFQMURUaU9KdG1ybmpjRk0xdlExWVM3UzVhamowCmdzUUN5Vy9i
            TmltQmhyaEJzTlMreWhuekEvTkdjUmx3Z3BBWHVpSGVuU3MKLS0tIFZybHZPWm40
            VGx5endrL0UwNXpVcUd6VnlVbWZHTFUyUVpMUXA0YVE2WjQKRxoJWosMAWlmV3++
            ehlO07B/jt1R91KKP2NRJSu/NSQCP8s3Go51n6QDvoQSJ+RVQA89LtuhRaqMLUwy
            Z3p8Bg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL031Q1Dd6yu310sGwE4++BdJIad4gApbWlsPpMI8Mcx sander@linux
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDEyU043QSB6aWJV
            SndreGhzbFM3SzYvU09RNkVnK2NadStFa1IyRGJPVEhsRTFEUlUwCkhveTdHVWJm
            di9nZTNkWnpWbGRzUGdHem5ocUdJWEprVE03Qi9qdWtPdW8KLS0tIFUydi9QNld3
            Rk9DVnpINTFScW1vb0NFWSt6bkI1aHluWTMrRS9SdjNCc2MKAc0xbpCtbHF8qxfJ
            Mz1ZHSVGpazauOPBpxI6wFT590QXiwGWVUprILrdb+76CHDGWoK9NLDLKL0lywbY
            evZVog==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPXFrU1bBLmiCk6/kDtrY8hBwZH1G3aLo8w/5psKz6rz sanlys@nixos
    lastmodified: "2026-06-16T13:19:49Z"
    mac: ENC[AES256_GCM,data:5HHdbTXHMz5R9zKpVKSxfPuUbm5Wp6OMIc48uCVwuG0OII7FXXX6PUDGba8bFQN9/TnYZmg649RfNmVyjVjmSILanAfwyJWcXuMnyjakIhQlsvMRkuHCDAsHKVE47jNeQDjfGQZ85mqBEx+vgWmLXXfIjDdRQrcKCQ7eJVBtAbc=,iv:ntuMCTs8uZrIt6lk1PxIVpwcFOQYppdhN30If7IHIkI=,tag:uo/n7bTR+6hMKh3UGzRv5w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
