apiVersion: ENC[AES256_GCM,data:nZs=,iv:NryJeHS01KmT+VvRxk0kGCv2oEIXCx2frJRa6O/5MFY=,tag:j+q4CoSvhSjuEEhyzWdzdw==,type:str]
kind: ENC[AES256_GCM,data:bZVGdTIX,iv:bjEXwsaookTv3Dtb/NcyOdM2t8d4h9Vhd5tqHdIKN6w=,tag:t1kh3Qq4UpRz4MN/kS42Jg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6ncuOuroHdgWtes=,iv:GHMRJQSDNSkojlnIbDPrbdWCg0Gy4+Q8RdlwoKRy/Gc=,tag:6nXuAFXaomgxoy3uC9UfmQ==,type:str]
    namespace: ENC[AES256_GCM,data:Fkt6aw==,iv:MIaHgdKH7MFknBO+4wwxrThPPayk5nnOC5JpxFTdZ3c=,tag:gOw4u3ptc+9omPSHa5zvFg==,type:str]
type: ENC[AES256_GCM,data:y81gIaHi,iv:RuMse2xyY7y2w6/xgK0knome+EZ4DgDwPOpeyKAoaig=,tag:GjGqeuWcJM9wyYmBLKojjQ==,type:str]
stringData:
    frpc.toml: ENC[AES256_GCM,data:LK8U95rJ5dyezb4Qvehzt1xNarpdfWVShPG6qlsF8CSKRFQkonFG7Ewb63jSGdjh8RjVyyx6oThj8DF4uAtO2KqsX8tMJoE7Osv7pcLkB/6ZOpARWvyZ6SWD1v5dU5n4VKeadoUUjDBGi3uyljXuJPW5a4nRpC7mQp2s3PsS1iy/JXFgGyXs0pJzoWgr/6JOV5GHvWXflfpJlLZgsLXdE6d6rlyA+wRASUxYc8OVImqbtPotdSvSr84y1+6ScIKemR8+uRJr+YYJl/cCHJxD2K9L/zI7BtPZsFJ3K8AfelMoLgV/8U9Tf3TlokTu4aip7Egix5395hTWtyYX7dh1m1THa6b0FjS6oWOGZD6XfVIE310gLSX9s9Z366a/ufMQIxwK51xmxwUKW2gX9wFIPxSj2dRO0tith//CmSgzaRA4QN1yQMtqhn/TawBa/TTMcPAo+hirqUGfplcMbh4F7ODbhP/5M5NZ3UEzorthhZeW7XrulLL70ZAwSGORl3sVfw2y8BiCall187MdygPWvn+rR0YsgLORic+SNMSUMKQ0jbG93OxEkDAEubbWjYW9wqyrMeQrgAz/PINQrLOPvFA6ukzBkXt+81vHSC69V2yHP8wWdLyE6mcDAdpFlVoHdq9FWarEw1FQE7F87Q==,iv:pI4UP26aqoEBD//gvtzj3DmGl4VXvQ100fvQqUFvJsM=,tag:RzXNUInnMX6daWy8Zz2l8w==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvT+ITNOzjlDdcTk9kdYLrGYd0EJw6kMr6Ynw9165wR sander@nixos-laptop
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE9hRWxSdyBEWXNI
            cHc2MjRhN0p0RVpQZUNZODBOL3gzdXZnayt3MmcrRlNvamRLUVRjCkxKVnVHcGU4
            MGZ5TEg3T3pJUFYzZUtqbllrTUEwUmxYZXZ0R21iNnlLeFUKLS0tIDBlazdERVZl
            dkNmbzhWTGFIMTRUZy9QKzRFQjg1YW81Zmg5TDAxL3lBQkUKzD4sjtYUlVFvPjzl
            oxlw7wbxJC21GP5vKYbGc7s5S+Yk1gbbZTWDVxoGjeK07JaZi33KtiHk/vV9jJWI
            5hCPJw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGhMesnzIJ89Ic38a3cOFUtiqE/No4FRFkhX+IqIIO3S sander@nixos
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHZpQ3Y3dyArYVZr
            OVNNS0RlZnBrb21NNTIyaElUKzhBWExIQk04aGx1eUJnRDJrOXlVCmRyOEk3cWNr
            MHdsS0VhN3NVbnJ0V1FBWHhLTGhLMnhsamplU3o0TWRsdVkKLS0tIHMwaEtxLzhT
            elZCcFBVSTc1YTU1WC8zbVQ2MHU3em9ESkR2QXVtZWRaVkkKOGJgSfzuSUklg8HL
            0Lx4za74M/oVrmSXthDUst4oba8UfNFpHe7ZzGN4Xtd0BnobPLwaZxy0vWbtQrR5
            xBRM6w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFHe3wCRa3OBsJZJsnXgDDbWaIB18hq0RKUzU1eGqoco slysa@asus-proart
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IElVbEhTQSBrc2t0
            L3pqN29VVEo3eFp1WGxsRHBuUC8zUmExKzJKM0xrQjB3RzZRMFg4CktnSEU5YnRE
            YjQ2aGhIRyt5SmxEQ25Bd2k3L0dGc1hMakl4MW0xNnBwWkkKLS0tIGZFWUkzREFn
            Q1ExRTFhanp3c2VscnR5bEJSb3dNVWxyazR4RTVSL1FTMTQK1Kgbb/CJ6AVXkOtc
            QCyk8gNpHBrVRDPuUYLZGhlc+SE2DgZlmgJPFTCUkXMB7Q5u3uGviv5tF0GujsF/
            UhRvfQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB3+7P7YnvA6ghkemNkLLwoFZL/oTBLUOIz8K5SyQwS6 slysa@desktop
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFBtM1RTUSBkVXdT
            Zk9oWkhBbEZTSlh3MFhNTmtLb3VrQXEwMEFIQmU4bGJGc2tSbkFrCkRjYkROQXY4
            SVR1T1BDWWQwU0QwakF1TDEwYndHYWlSOWRaTEVCbWlQNVUKLS0tIHNkZVF6SDE4
            L05yVk1ta0gzK2RGSU1yZ2dIeUxweW1UWWJiOGk1MEJGNW8KiiImbS66Ca4XV2JV
            gJDrjwgK3kOslx9VW/wy2RRKzVTYAnbXMVE62iW1YE6ZWrRq5Q/tygH0XkUiSzgK
            iwTj3Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age185wsded9nj5vsw58saezfj8wekkftmpsrhv9cd05ep3k5vap8ckqc9epjn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVm13TWdZeldCOTZLejRG
            cGt5QUVkNUZsWDFYLzRQNkV4ZFdCVzRHU0Y0CjRFR0Y4TUVudVBzNWdua0RpRXRw
            K3NLOGswVWlhWXAzV2trYS9qZDRFRmsKLS0tIGN6cW5NUTNBQlVOb3IwRGZDN1pn
            a3YwNlBTdkJJdE5GQnFRb1pWMkdsTzAKyem/9zFk7tUCV/84O1l2zy+PiRawSsUz
            0+pfqFoQKqmy1Psp6QdL2lU4KDs4AaRH0xuwgKwH6aQYC0esCSyGmw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL031Q1Dd6yu310sGwE4++BdJIad4gApbWlsPpMI8Mcx sander@linux
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG1XOCttdyBrNmhT
            RnFSRFp5bS8veE44SEpxbW10TS85d1k0M1FLNVU0N3QvOXQzN0NrClR0aTZabk9R
            YWF6OVppN093UXhQZUpaZENWbnEwLzdRaElwWVFxaHFOVkEKLS0tIHNUNGl4Q1p1
            UE0zNVZIOTVxUG0rSmVmZlkreHV6c0tXRkovWXAvWUR4SFkKFWEqI1yfwrl6+O0n
            QZg6fq8xGP6GWT0FefwLDoxufH8uhXVFX2Oiy25/fk3qIq8Fm4NTbMMB1A3kIRCG
            Zawtfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T14:45:17Z"
    mac: ENC[AES256_GCM,data:51RP5sck2VbIrpIoHpDN8mTtqE84asVzHNJ5WC3GTRzkRtb1n+PIIx0JoO8T0OTn8If7P0zTXoQjbA2ijCPXBynl77d9hM0SEv0Mz53SE8dhsPk805edpfvGriDa4kK0CyR+PB0uqT3alnKPBMUFzNgILDyLiPY4uUVGODzmhIo=,iv:wKaorMtvuM1lPy7zSdFmEeOC/nKRj20OUqri2T5wMf0=,tag:vVpfluIuTrEKrGwTYQHCZQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
