apiVersion: ENC[AES256_GCM,data:nZs=,iv:NryJeHS01KmT+VvRxk0kGCv2oEIXCx2frJRa6O/5MFY=,tag:j+q4CoSvhSjuEEhyzWdzdw==,type:str]
kind: ENC[AES256_GCM,data:bZVGdTIX,iv:bjEXwsaookTv3Dtb/NcyOdM2t8d4h9Vhd5tqHdIKN6w=,tag:t1kh3Qq4UpRz4MN/kS42Jg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6ncuOuroHdgWtes=,iv:GHMRJQSDNSkojlnIbDPrbdWCg0Gy4+Q8RdlwoKRy/Gc=,tag:6nXuAFXaomgxoy3uC9UfmQ==,type:str]
    namespace: ENC[AES256_GCM,data:Fkt6aw==,iv:MIaHgdKH7MFknBO+4wwxrThPPayk5nnOC5JpxFTdZ3c=,tag:gOw4u3ptc+9omPSHa5zvFg==,type:str]
type: ENC[AES256_GCM,data:y81gIaHi,iv:RuMse2xyY7y2w6/xgK0knome+EZ4DgDwPOpeyKAoaig=,tag:GjGqeuWcJM9wyYmBLKojjQ==,type:str]
stringData:
    frpc.toml: ENC[AES256_GCM,data:Ic/8KWt6W/cAKHH31VTSPLQLOCKSusJ8Cf2Gw4QJ2SG4Wp4/5zacjMJ0g6FfOzIkqTYqjIoJfHsGKtVDzcsefUlGXw/JngNW/Tp28HS9HShVhWDZMnnefhQSRZmcOJLLHfWwnqCJ2qfy7gnN+ciYybh9GCyvnjGLpACUt0jSiqhAbih/Y6Q1/zwCFVYQ7xkamFS2sRs/F2Cu9VPOE/Mnum1UXJlHDVoyTs3SRogqaDMm/WUeuM4qIOuusVBw0SpUd5vhEIQ/vRdpOTE2sjof1KFoK7OX3TgKhcIIvqC5e+2TuqItyUb4vQgZe4oLMt84GtD5dy23xwWiBdAp/ByXV9tGaqFsYEBO79KZ5FyCWAG8E4ipmF8CPk0N2VNSgcLPN40RavzE+ZPTVfmYoA+d8a3YIOMABHmlGS1zkPUmTL7CSed9m0PqXloWm9qVgySAHwijAPJ03BT3FvYWK3RTeHi10oBKr6qnDckus5IU/xxtw19rJ3ohZ8/DrPqOh8eoJRofJuI8KMiw7tOhTW0bb0aDHYCPClp317QPm2kf5smOmSOgAwnKP5h5RGqFTdcBge0BrSw015ptujHIQltGrwKTIFEg5kqBpbUwPsdwIkfTmDT67VUlscFAkZGFnESLgO00DdWe0q8+bEafCMMPbsLCyAIN2uN3wEXiUeTq+Fk7TgAfEYiYkbCCk2PvfcCqLpCivNrUrT1S0nndujtZmLq9f2rGKJm9C7JeefQtmQqMN0IBvN6eazo9z3S2s4rIlL5HqHe94hqj7bBV0udwpOnrRMyyMxhJhxUugU1QmCSxaCtg4ChyElCbz7hxvi/g3THTefYwy647jhdDzf5cLbr6iak/L480zi56iA+ENUML/UE8DMC3dOrWbjR04JSu3+OitgrnWFq1jt1aEOkoAMJ/UqQN0e1u,iv:efXRyqUsyXsVFXWXoFnCJJdG5tcAVaSA33k2MmixPS4=,tag:NongZuXrNM+GHdeTgcV8zg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE9hRWxSdyA3aS9m
            OGhMTitxNlFsOXpZekVSdHBXVkN5RXRKVHhtQXVPRlBrMUw0cmpjCk0vV2dueHlw
            NkhRYmJOWGFPVU9WY09aVUdSV20raXZCTnEvby9kbEJraVEKLS0tIGRvVTZTWHVW
            OGJQdURBbkNiendLN3Jlc3B5ZXBFRHF4VHhoMUxoamhaNk0KR2qjbMss5MGb1jDW
            mS8Yn/5YmtX7SGdjsjM3pBE8UQSkZFubGvIfQ9xkgEg2S6SHFqnPn7/Ihy4UqtwD
            itNllw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvT+ITNOzjlDdcTk9kdYLrGYd0EJw6kMr6Ynw9165wR sander@nixos-laptop
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHZpQ3Y3dyBxK0tl
            L2VBQU5WczFIQW9IMW9mS1V0bXdJUFdKb2Q5alhNZWR4QnFLM0dBCm5vOEkzbEt6
            VDAyNVBsRGJWTmQvN3FuMklIcUNza1lsRXBHOFdSNlhpSEUKLS0tIFY5dllBY2tM
            TG9RRXFpemdmV0dRTW5CN3V1bzZlS09nSEJnM09pOTZLNEUKPmPY8xiOw7GuVBhU
            +hsNyqfKTiZii5EqHX7YvXsPGO6J/G0Xucq8QYd6Pic13eYwJZ8eml9c9QOMfF7w
            lDqsNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGhMesnzIJ89Ic38a3cOFUtiqE/No4FRFkhX+IqIIO3S sander@nixos
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IElVbEhTQSBkcXps
            eGtpdW9jQldpZGR4SXI4dWtQa2xhK1dpMm5TRDEzcHpmVXpSaFM0CjVJTlRIbVhN
            VDhlOFBMd1kyVW1Qb1FiMWNOdENDT3FBdkhKM0VzZWlDcmsKLS0tIGpRb1hIN3ZF
            QTBxcjczblBxbGcveEZPM3Z1enMvMDBwbFZoT0F4N0YvNFkKFsK4Sd1WYHtx3kVg
            8317q1Muz+kLqqUbUPsJstVE/e8dDxlfraL29Uzm6H0hLLXb6s42L6J0bL7rfwOh
            w9D4Bg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFHe3wCRa3OBsJZJsnXgDDbWaIB18hq0RKUzU1eGqoco slysa@asus-proart
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFBtM1RTUSBEd3JL
            ajRvTUZMY1BSN0lXeEU3eFNEaXZIZkd0blJLZmpsSnYzRndpcWgwCkNTOWNKQUpW
            UkZTUGk4cGRJeFFjSjJ1N1Z6dnBMNlZKVkNZWll6L0VOVVUKLS0tIDA2YTFwSzdV
            VTdZM08zeVZrRG5BazJPcU91WTVaY3dTN2N6ZmxIaXhKZ2sK3aT7uqtF8fZdgeWg
            cs+KpGXdVxORlHOTFIdAwG5eM8JKlUGkCb32YnryLbPwbNHrYujLyGiLHuaVHN/4
            q7dHSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB3+7P7YnvA6ghkemNkLLwoFZL/oTBLUOIz8K5SyQwS6 slysa@desktop
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZ3ZxNTFMUDN6QTBrUi8y
            OXZVUWJNQnZoVmoxQlNRNmxSNkVQcENwVTBJClhVZnVibVo3dHh2Zi8vL1Q3Vk43
            VVJ4Vk5Mb1BKQ1pxTTdaN3R1cGVQNUEKLS0tIDVYcTZkdjdzQjJLMUJIL2hobVhG
            UW1LeFlsV0g3QnFwV2JGaVNOQys1eVkKFv6WowHy7XolSe3A5eYBOUw4FCjheu+f
            +eFAnfAy0jkYQhwX+fCwgJYDG3oqg9wi7CfyADzyMdKVBnkbE/SVqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age185wsded9nj5vsw58saezfj8wekkftmpsrhv9cd05ep3k5vap8ckqc9epjn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG1XOCttdyBLbmFV
            c3loU3ltdTR2RGZ3QUh2SWFXVStQdDZieVVweTJ1bnczY2ZBdnlVClRjYlNjdlhO
            ZWtDSFNwTWZ4S2FibkJSRjJkeGw4bDQ0M0NKVS82WUE0eDQKLS0tIHRGQlJkSWNm
            anBETG85dWNRT1NTakw3VkZ4TW9TcVl2NkFVa0IzV2xKNmsKYbyxrAme3BckLzUq
            omOmI2g2gOGGR9SHAxj095syth0cEGoodsqWBgx+3s+U0JUwPVkO+4d9wt2ALJu8
            AJWM/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL031Q1Dd6yu310sGwE4++BdJIad4gApbWlsPpMI8Mcx sander@linux
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDEyU043QSBZa3JB
            TUpDSWUvU1gxSzRxMlJ3R2xTbExwMm9UakZEenU2eCtiend2SEFBCnVtUldVL3hi
            STViSkVqSU1GMyszNDlXOXJWZDZZWS9mVU5Yb2UwTFYyMVEKLS0tIE9kVERHbXNn
            N1ZzRE9UUDd5V205R3RIT1g2VUN2OUtlRkZiWkkrbUhESmcKOK3oTwbyf9FP9jSO
            URsuwVzkc55JEg7eoMQ8etbiG764sMySSqZcPA6TibFPm+Gch/TP38sihv5WVdH0
            TX7nTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPXFrU1bBLmiCk6/kDtrY8hBwZH1G3aLo8w/5psKz6rz sanlys@nixos
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdqWWNkdyBMSG9V
            L0phMWlJR3pLWUNUM2lsSzFteUgzeHV5a2w1Q1k4VHgxQWtiQnhVCjRwcjNtVnla
            L2hrdEVjYVc0d2dJSW1YVDJjVEtjRkNYcEZYWUZwNUp2Rk0KLS0tIHFXN0c3cjRO
            TW95Vm54elg2Ri9UTUtod0lFVzE1Mlo5QkhWSXpQNXh1T1kKEOIvL1hZF2zIEGMg
            qgB43cwhZMTivKscMABpXoK8KFkdn1HWKvqo4PNNX9gCQeEEayb//tKxkZxgtR3O
            UakzrA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJxVXIN2uJgZC7mU0yZXHkEwp9VPTnlO4pEHVWs/7KXa sanderlysakermoen@Sanders-MacBook-Pro.local
    lastmodified: "2026-06-16T13:19:49Z"
    mac: ENC[AES256_GCM,data:5HHdbTXHMz5R9zKpVKSxfPuUbm5Wp6OMIc48uCVwuG0OII7FXXX6PUDGba8bFQN9/TnYZmg649RfNmVyjVjmSILanAfwyJWcXuMnyjakIhQlsvMRkuHCDAsHKVE47jNeQDjfGQZ85mqBEx+vgWmLXXfIjDdRQrcKCQ7eJVBtAbc=,iv:ntuMCTs8uZrIt6lk1PxIVpwcFOQYppdhN30If7IHIkI=,tag:uo/n7bTR+6hMKh3UGzRv5w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
