apiVersion: ENC[AES256_GCM,data:nZs=,iv:NryJeHS01KmT+VvRxk0kGCv2oEIXCx2frJRa6O/5MFY=,tag:j+q4CoSvhSjuEEhyzWdzdw==,type:str]
kind: ENC[AES256_GCM,data:bZVGdTIX,iv:bjEXwsaookTv3Dtb/NcyOdM2t8d4h9Vhd5tqHdIKN6w=,tag:t1kh3Qq4UpRz4MN/kS42Jg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6ncuOuroHdgWtes=,iv:GHMRJQSDNSkojlnIbDPrbdWCg0Gy4+Q8RdlwoKRy/Gc=,tag:6nXuAFXaomgxoy3uC9UfmQ==,type:str]
    namespace: ENC[AES256_GCM,data:Fkt6aw==,iv:MIaHgdKH7MFknBO+4wwxrThPPayk5nnOC5JpxFTdZ3c=,tag:gOw4u3ptc+9omPSHa5zvFg==,type:str]
type: ENC[AES256_GCM,data:y81gIaHi,iv:RuMse2xyY7y2w6/xgK0knome+EZ4DgDwPOpeyKAoaig=,tag:GjGqeuWcJM9wyYmBLKojjQ==,type:str]
stringData:
    frpc.toml: ENC[AES256_GCM,data:rM0sVHA51UdNCOmYnxvBDf2HFK/nGY+RTr+V3rnYGVH8T/Anxs12bHWYBLB0wc22IxbcSexzvpNSahEwr+z489sJHvoBo5f+vSlqp5K18OquXFSl/TViWdIfcsJ3SpJw8FUc1UwJsq9WpqjghtPN2FpC0DNA3CO2ac8ASQdXF1VWf5Zo+IzURIm95JzsXhQVORJa102JvwQdgB5x4104bBo8qmqpwC5Dyjt9/eLu65LVPqAYQf6uPK+XjnU0FS90Py1nR9R7+71dqRhyPpFTZf+Rf3tGtslJh1RuaDFS9720MYdo3faYTSxEU/H+AhEtRAZcDdHiaylA/hw0yy57ROfc2aoKI8fHVFenn9b5SBOxaA0us/UXFgbn+SEexmvjcdvR0r9bnIjk6BseuD41tNa3L9+14wCDuCLI7hfZoAox+4nfvd6Z/g5VVYSRJqIVt3SwOHIovWh1dIRcbNT1fLiqu2tLwWxjLryD61w3anSbi+QyVGrPt08tdLqkbcF3Zee0R0cqaZc1GP9T3XCMRbYh4ANXFWXCGUx4SSW4OtOVrzodd0HFW+YqaUPIRI2BZ1/mT0qu/tErhHzAcbpXxQ+k00EJ+shViVXMl5BaX8WQpQYobXf+wGgvSNpD96X5GqQdi52et4BBYcAuuUjlN3NV89UeLYfc/ZL+XEYD/zSRqp5pHYhP4LdGYf4LNV6mvtTqfrlhVgZVnLIWm/DKCxkef6IWwNPJdnHA4qrHSlEm4JfTS255h0BBPg6scyyEbXFpZnghDxuR7ecPjCjkbGrPWOf8SA==,iv:oUMILO/JxqjEPiSVFSSLYoeLugPgy0qNejru8gzWZDw=,tag:/BccK5a2k4gxbN34+yNjZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE9hRWxSdyBEWXNI
            cHc2MjRhN0p0RVpQZUNZODBOL3gzdXZnayt3MmcrRlNvamRLUVRjCkxKVnVHcGU4
            MGZ5TEg3T3pJUFYzZUtqbllrTUEwUmxYZXZ0R21iNnlLeFUKLS0tIDBlazdERVZl
            dkNmbzhWTGFIMTRUZy9QKzRFQjg1YW81Zmg5TDAxL3lBQkUKzD4sjtYUlVFvPjzl
            oxlw7wbxJC21GP5vKYbGc7s5S+Yk1gbbZTWDVxoGjeK07JaZi33KtiHk/vV9jJWI
            5hCPJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvT+ITNOzjlDdcTk9kdYLrGYd0EJw6kMr6Ynw9165wR sander@nixos-laptop
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHZpQ3Y3dyArYVZr
            OVNNS0RlZnBrb21NNTIyaElUKzhBWExIQk04aGx1eUJnRDJrOXlVCmRyOEk3cWNr
            MHdsS0VhN3NVbnJ0V1FBWHhLTGhLMnhsamplU3o0TWRsdVkKLS0tIHMwaEtxLzhT
            elZCcFBVSTc1YTU1WC8zbVQ2MHU3em9ESkR2QXVtZWRaVkkKOGJgSfzuSUklg8HL
            0Lx4za74M/oVrmSXthDUst4oba8UfNFpHe7ZzGN4Xtd0BnobPLwaZxy0vWbtQrR5
            xBRM6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGhMesnzIJ89Ic38a3cOFUtiqE/No4FRFkhX+IqIIO3S sander@nixos
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IElVbEhTQSBrc2t0
            L3pqN29VVEo3eFp1WGxsRHBuUC8zUmExKzJKM0xrQjB3RzZRMFg4CktnSEU5YnRE
            YjQ2aGhIRyt5SmxEQ25Bd2k3L0dGc1hMakl4MW0xNnBwWkkKLS0tIGZFWUkzREFn
            Q1ExRTFhanp3c2VscnR5bEJSb3dNVWxyazR4RTVSL1FTMTQK1Kgbb/CJ6AVXkOtc
            QCyk8gNpHBrVRDPuUYLZGhlc+SE2DgZlmgJPFTCUkXMB7Q5u3uGviv5tF0GujsF/
            UhRvfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFHe3wCRa3OBsJZJsnXgDDbWaIB18hq0RKUzU1eGqoco slysa@asus-proart
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFBtM1RTUSBkVXdT
            Zk9oWkhBbEZTSlh3MFhNTmtLb3VrQXEwMEFIQmU4bGJGc2tSbkFrCkRjYkROQXY4
            SVR1T1BDWWQwU0QwakF1TDEwYndHYWlSOWRaTEVCbWlQNVUKLS0tIHNkZVF6SDE4
            L05yVk1ta0gzK2RGSU1yZ2dIeUxweW1UWWJiOGk1MEJGNW8KiiImbS66Ca4XV2JV
            gJDrjwgK3kOslx9VW/wy2RRKzVTYAnbXMVE62iW1YE6ZWrRq5Q/tygH0XkUiSzgK
            iwTj3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB3+7P7YnvA6ghkemNkLLwoFZL/oTBLUOIz8K5SyQwS6 slysa@desktop
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVm13TWdZeldCOTZLejRG
            cGt5QUVkNUZsWDFYLzRQNkV4ZFdCVzRHU0Y0CjRFR0Y4TUVudVBzNWdua0RpRXRw
            K3NLOGswVWlhWXAzV2trYS9qZDRFRmsKLS0tIGN6cW5NUTNBQlVOb3IwRGZDN1pn
            a3YwNlBTdkJJdE5GQnFRb1pWMkdsTzAKyem/9zFk7tUCV/84O1l2zy+PiRawSsUz
            0+pfqFoQKqmy1Psp6QdL2lU4KDs4AaRH0xuwgKwH6aQYC0esCSyGmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age185wsded9nj5vsw58saezfj8wekkftmpsrhv9cd05ep3k5vap8ckqc9epjn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG1XOCttdyBrNmhT
            RnFSRFp5bS8veE44SEpxbW10TS85d1k0M1FLNVU0N3QvOXQzN0NrClR0aTZabk9R
            YWF6OVppN093UXhQZUpaZENWbnEwLzdRaElwWVFxaHFOVkEKLS0tIHNUNGl4Q1p1
            UE0zNVZIOTVxUG0rSmVmZlkreHV6c0tXRkovWXAvWUR4SFkKFWEqI1yfwrl6+O0n
            QZg6fq8xGP6GWT0FefwLDoxufH8uhXVFX2Oiy25/fk3qIq8Fm4NTbMMB1A3kIRCG
            Zawtfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL031Q1Dd6yu310sGwE4++BdJIad4gApbWlsPpMI8Mcx sander@linux
    lastmodified: "2026-05-27T19:09:04Z"
    mac: ENC[AES256_GCM,data:KCZgdT8IrYHJLSXIUd00qf2spK8eKxWEav77jXyjKwPBMRkGyEknaS+nzSaoQ7oC8Nt5wxNkejOzgpzkpgSABP0hRkkfp7O23o2gb7oW8zCIwZy7ujTy4i5B/8JJa4LEdQm0sXB4EuavdClloA3dwm9ZyGj3o/TSpPySdtOcIvQ=,iv:qmTtxkB/rKh/pb0XlE7biXCRIUjz1mZtd801r8H4ij8=,tag:lF6HHFFgwc12ouJun1cQxQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
