apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data
  namespace: nfs-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block-ssd
  resources:
    requests:
      storage: 30Gi
