apiVersion: v1
kind: Service
metadata:
  name: nfs
  namespace: nfs-test
spec:
  selector:
    app: nfs-server
  type: LoadBalancer
  ports:
    - name: nfs
      port: 2049
      targetPort: 2049
      protocol: TCP
    - name: nfs-udp
      port: 2049
      targetPort: 2049
      protocol: UDP
    - name: rpcbind
      port: 111
      targetPort: 111
      protocol: TCP
    - name: rpcbind-udp
      port: 111
      targetPort: 111
      protocol: UDP
    - name: mountd
      port: 20048
      targetPort: 20048
      protocol: TCP
    - name: mountd-udp
      port: 20048
      targetPort: 20048
      protocol: UDP
    - name: statd
      port: 662
      targetPort: 662
      protocol: TCP
    - name: statd-udp
      port: 662
      targetPort: 662
      protocol: UDP
    - name: lockd
      port: 32803
      targetPort: 32803
      protocol: TCP
    - name: lockd-udp
      port: 32769
      targetPort: 32769
      protocol: UDP
