apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: tobbeos
data:
  myconf.conf: |
    server {
      listen 80;
      server_name _;

      root /usr/share/nginx/html;

      location / {
          try_files $uri $uri/ /index.html;
      }
    }
