apiVersion: batch/v1
kind: CronJob
metadata:
  name: git-sync-job
  namespace: tobbeos
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app: tobbeos
                  topologyKey: kubernetes.io/hostname
          volumes:
            - name: tobbeos
              persistentVolumeClaim:
                claimName: tobbeos-pvc
          containers:
            - name: git-sync
              image: alpine/git:latest
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: tobbeos
                  mountPath: /repo
              env:
                - name: GIT_REPO
                  value: "https://github.com/TobbeBob123/TobbeOS_Website.git"
                - name: GIT_BRANCH
                  value: "master"
              resources:
                requests:
                  cpu: "100m"
                  memory: "128Mi"
                limits:
                  cpu: "500m"
                  memory: "256Mi"
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  cd /repo
                  if [ -d .git ]; then
                    echo "Updating existing repository..."
                    git fetch --depth=1 origin $GIT_BRANCH
                    git reset --hard origin/$GIT_BRANCH
                    git clean -fdx
                  else
                    echo "Cloning repository..."
                    rm -rf /repo/*
                    git clone --depth=1 --branch $GIT_BRANCH $GIT_REPO /repo
                  fi
                  echo "done"
                  exit
