apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager-discord
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/Sanlys/kubernetes.git
    targetRevision: main
    path: cluster/prod/platform/monitoring/alertmanager-discord
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

