apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.rook.io/release
    chart: rook-ceph-cluster
    targetRevision: v1.20.6
    helm:
      values: |
        cephImage:
          imagePullPolicy: IfNotPresent
        cephClusterSpec:
          mon:
            allowMultiplePerNode: false
          mgr:
            allowMultiplePerNode: false
          crashCollector:
            disable: false
          security:
            cephx:
              daemon:
                keyRotationPolicy: KeyGeneration
                keyGeneration: 2
          storage:
            useAllNodes: true
            useAllDevices: true
          dashboard:
            enabled: true
            ssl: false
        toolbox:
          enabled: true
        monitoring:
          enabled: true
          createPrometheusRules: true
        cephObjectStores:
          - name: ceph-objectstore
            spec:
              metadataPool:
                failureDomain: host
                replicated:
                  size: 3
                deviceClass: ssd
              dataPool:
                failureDomain: host
                erasureCoded:
                  dataChunks: 2
                  codingChunks: 1
                deviceClass: hdd
                parameters:
                  bulk: "true"
              preservePoolsOnDelete: true
              gateway:
                port: 80
                resources:
                  limits:
                    memory: "2Gi"
                  requests:
                    cpu: "1000m"
                    memory: "1Gi"
                instances: 1
                priorityClassName: system-cluster-critical
        ingress:
          dashboard:
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-internal
            host:
              name: ceph.k8s.lysakermoen.com
            tls:
              - hosts:
                - ceph.k8s.lysakermoen.com
                secretName: ceph-k8s-lysakermoen-com

  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    automated: { prune: true, selfHeal: false }
    syncOptions: [ServerSideApply=true]

