apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trilium-data
  namespace: trilium
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block-ssd
  resources:
    requests:
      storage: 5Gi
