{
 "title": "Overview",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Cluster usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "ceph_cluster_total_bytes{}", "legendFormat": "Total" },
    {
     "expr": "ceph_cluster_total_used_bytes{}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Available Capacity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-((ceph_cluster_total_bytes{}-ceph_cluster_total_used_bytes{})/ceph_cluster_total_bytes{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MC Server logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"minecraft\"}"
    }
   ]
  },
  {
   "title": "OSD Utilization",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(5, sort_desc(1 - (ceph_osd_stat_bytes - ceph_osd_stat_bytes_used)/ ceph_osd_stat_bytes))",
     "legendFormat": "__auto"
    },
    { "expr": "ceph_osd_stat_bytes{}", "legendFormat": "__auto" },
    { "expr": "ceph_osd_stat_bytes_used{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Write latency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(ceph_osd_op_w_latency_sum[1m]) / rate(ceph_osd_op_w_latency_count[1m]) >= 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write latency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(ceph_osd_op_r_latency_sum[1m]) / rate(ceph_osd_op_r_latency_count[1m]) >= 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kube API SLA",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apiserver_request:availability30d{verb=\"all\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 18, "w": 11, "x": 13, "y": 12 } }
 ]
}