apiVersion: v1
kind: Service
metadata:
  name: cdi-uploadproxy-lb
  namespace: cdi
spec:
  type: LoadBalancer
  selector:
    cdi.kubevirt.io: cdi-uploadproxy
  ports:
    - name: https
      port: 443
      targetPort: 8443
