apiVersion: ENC[AES256_GCM,data:teo=,iv:Rq/gj3wbatreFSDYHa2u9TFpweayDe5LcSOu+0tGV+w=,tag:2/FagWM/FptPWr5mpg8TFQ==,type:str]
data:
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:e49pqQ2cI4MZLywCwMDGww==,iv:z+jtEfZbmTzu/8zp2tjnxrkQxNqJ8TgjjasiuV05S3s=,tag:qw1nnnQb0fkSYI7HsyRI8w==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:j/pSjHR5wXvUyXC4Wz7tAS5f3n228hfVGB6yk9JtX/duJ2d/6CN3eDFFeBo=,iv:Dq7y4eTrCctCy0teybjfMMDIr9aTO2ub5jbW2WXTJrs=,tag:C3cIlpJ9yiPAJMuxFksS3w==,type:str]
    TRILIUM_TOKEN: ENC[AES256_GCM,data:R09qnWb+9ERagReVJZg5crFPpdgFw9DlGbsugKocXDrySB94tdxbvX3bEbIc3cGIN0JFngSxP38jeDXQ/L5G44f0EamAIgb8J0JdqA==,iv:ZSqMbaRYNQV7H2Hy3gDybnDjFKPyYDp3GKsFx+SrlVQ=,tag:9To8YNfNP85/Vk4UPM0gEA==,type:str]
kind: ENC[AES256_GCM,data:ZUBVKJMt,iv:02Yp/adqPvSWiOFBIQb27yUeH5oeb40Oet/fyqyOvWw=,tag:FMLHh2WmU5tFv0oL1yQA8g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:odiAdSWhqswlz2Or8zDQogyLuQ==,iv:+5bIXkUiy0ASl9pnCscQTL4gA2nnzBG7IpMybzNze6o=,tag:yzxcbpvy8AI18DNrhg+hOw==,type:str]
    namespace: ENC[AES256_GCM,data:WHwMEbt+zV6Zc4M=,iv:GWom+W5zoxcrD7OKvByP2KblLKDqaF/+7KnL4rbVYgU=,tag:WViX0aTrH8ZFUaWn2zNyJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE9hRWxSdyBuQ0VX
            ZGJjRENNZHJhNVAwdnBFbjVxV0xkT3JKZzVscUxFSjcvVkJmMGdVCnZGR3k3Ynpy
            UFphaW8rUlN0WExrVER3Wjg0ME10OUlYZ0VZWC9rRkIvczgKLS0tIEIzb0JjaE5u
            ekpRREhIanppYlViWTI1VXVCU0RZMFFwYVhUUVRrQ3dEcVkK86xlJGNlnEdnyq0B
            jWyMrqD7fItxnMNf9noEwXfYcVBO73iogjNKU3Ev8/gyKkfjVgYM+tXGkoNh5icz
            rcOaGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvT+ITNOzjlDdcTk9kdYLrGYd0EJw6kMr6Ynw9165wR sander@nixos-laptop
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHZpQ3Y3dyBTQ0Fm
            aS9WL3RZL29aMWpwQVJWU3k3WjdXZi9NV0N6NmFHTmNOeFZNbTNBCnlsKzh0MSth
            VGg0Zk1nWXNURy80bGhkSVlhQ3U1MzRLMllqL2djY0w4cGsKLS0tIGpxZzBHRUQv
            bFZjK3FtM1JYSEIybU9XZXJ2SlpQZlpqUWxBSVlGcTN5MTQKdQYmo4z6D/c5gMCv
            3szQXQq/7VO/RMemVP4mWhhWwdVt5aAszoALsIa+MbJd7jGkO8mtZJiCGLz01/I6
            sKfnCQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGhMesnzIJ89Ic38a3cOFUtiqE/No4FRFkhX+IqIIO3S sander@nixos
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IElVbEhTQSBKTkNT
            UnhBQldmN3pFOEdtR0F1YVFHWkhNZWw1bzBqNmdyMUsxVjlPMEM0CmdJbEtvMC9o
            THpVWW1nakpwbU1HV1daSGNjRmJoWmg2RXFNYmNJa1ozS1kKLS0tIElOckg4NmtC
            RS8xWjJ6cHNadVU5QXkrQjFpdnd1VTZIZmJXdnNNWWxqWVUKhRCIrgvMiFuCbxss
            ETzeDkGKTRhfncgKeVh33QNPmOJJmNf1+nuOHiKxEqhBXYmlBxXFod/hV6YizW14
            dnYQCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFHe3wCRa3OBsJZJsnXgDDbWaIB18hq0RKUzU1eGqoco slysa@asus-proart
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFBtM1RTUSB1VUZy
            TlJKMHEyUzlyck5XU0tNSlBEdlNwUXRNK25YN2NtRG1UaUN3WDBFCnZjMkRBZURH
            RzFBY3dnTHRjcXh4M3ExNlJHWENEVHA3YVBoNDlURzZLSVUKLS0tIEFrRGtiVTRO
            TGhHR2NpeG1YckhkaUlSek1XUjMrUkdmUml3YTJDYW9DR0EK/HU0cjnRcWPa85x2
            0ZjN1uIpEChFG3h2E8Mp2xmAO2IqynKsooMp93o/D975k6ZjbsuPl/kt3cVZtKFr
            U7s3xg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB3+7P7YnvA6ghkemNkLLwoFZL/oTBLUOIz8K5SyQwS6 slysa@desktop
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwanU1NXhMRGI3LzQ5cE9s
            bWRoSkNpREdsV2ptcm13YkZPZ29zVWdkMlVJCjVjeUxpdTljZUJKV1grbnZOMzRV
            TUMrU3lTWUo5ZVhrRXJNSlNWb1BlQWcKLS0tIFpvV1QzM1MzV0pZbVQ5cWRCVTMr
            S1pOTjRxdHQ2bmRMTEEzL0xoYVlCN2cKNdmaS+elbItnxxtc7SFGFxCb3wNAeklP
            BWT36wp4dPIk1pCaEhitOm3u2eeDjq65/7JGwnpwhzO/cIJd2fizDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age185wsded9nj5vsw58saezfj8wekkftmpsrhv9cd05ep3k5vap8ckqc9epjn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG1XOCttdyBlRlU2
            Vm5Kd1g0OGVpYytlbWR6aU9xVVFzZkJmYXlnY1Z4eDVxUkVYNlgwCk5LK3h5bnZa
            S1U3aU1wZituVmh3NHVGRTNBOElNMU92b1Z0cGdXcnVPNkEKLS0tIHJVaFJpeXpJ
            cUhVVm9VZEh2YTMvOGpzaTYzeG5JcjRFZHhUSEdaRUk4VlUKFI5kv+WOlEz5GYcs
            7kyOrtB+0WLncnjBLCHsNDurxlfBy47RdeIZ31hQRersrwXaOnluVQplKlJlh1iv
            lH3k2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL031Q1Dd6yu310sGwE4++BdJIad4gApbWlsPpMI8Mcx sander@linux
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDEyU043QSBtamZM
            VkdOWXg1cExtdGdiQ3hGNURiQVhaS29QN3E1aXQ3N1hGcDJ6SEhZCkJsekhEOW9r
            T0Q0UHpYNjAydVc0WTVNYnNaMmZvMDFQK09ITVMzSzlQQ1EKLS0tIDNYa2dRRmJI
            T0NsczlDSGhGbUlHTlVmMDdvSUsxZExxQ2JDQzRoUjdRQU0KrR7lTRF+zMQFnG3Q
            6MWhhWw4BUIkRYsktBekQ1Qf83oxaqmZiSXwnsSpa8ciVKOc3mtvB+wAd+UsgG51
            wCQr/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPXFrU1bBLmiCk6/kDtrY8hBwZH1G3aLo8w/5psKz6rz sanlys@nixos
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdqWWNkdyB4VUxH
            eXJaMGE1Z1pIQ091OXBlQ3BLU00vMEZqdHN5c0RWem1FSGFmdkZVClZtbEFJUXI2
            T2VDc3dVankweVh0amdiWW85SVlaRGhrN1B1ZTJ0cFNXeWMKLS0tIHJkZlk0ZlBD
            MXpiZFNGZXlTbElkSGo0L1I5VEZST2pOK21acjY1ajVCVDQKLQ+rQ06I8XxaKtse
            WcFcaUzrSHS8f4DOP7IVl7mSfH8JWt9Lg+G90Dp/BGOUbFgs03gQwyHZy9VBKQy5
            V7NAnw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJxVXIN2uJgZC7mU0yZXHkEwp9VPTnlO4pEHVWs/7KXa sanderlysakermoen@Sanders-MacBook-Pro.local
    lastmodified: "2026-07-31T22:02:07Z"
    mac: ENC[AES256_GCM,data:2hcf9DERuxFcNBkRwPVvow2Bx6l8UQdOyY3Gmb6tya0yf5RW86DcVSO6grQh7FRPp69h6y6AU1Rp5SH4nb5vwlFEs09atXkYwAqSAC1VCuf76WvK6H9K1gj9e6pcmsJZNct4lrVM4grcq9Euy1mXY2cyrHXaXmuolmBemE6sq+s=,iv:dYgr+1bzJCu9MKJgzrngiGyZF0NJSzEi4idRrN2OJ1E=,tag:QnQac26n7mKucpvzZjgABA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
