apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-nfs-my-nfs-a
  namespace: rook-ceph 
spec:
  ports:
    - name: nfs
      port: 2049
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: rook-ceph-nfs
    ceph_nfs: my-nfs
    instance: a
